cluster_namespace:
  description: "Manages a Morpheus Cluster Namespace resource."
  templates:
    tenantIds:
      set:
        computed_optional_required: computed_optional
        description: List of tenant account IDs that are allowed access.
        element_type:
          int64: {}
    resourcePermissions:
      single_nested:
        computed_optional_required: optional
        description: Resource permissions for group and service plan access.
        attributes:
        - name: all
          bool:
            computed_optional_required: optional
            description: Pass true to allow access to all groups.
        - name: group_ids
          list:
            computed_optional_required: computed_optional
            description: List of site/group IDs allowed access.
            element_type:
              int64: {}
        - name: all_plans
          bool:
            computed_optional_required: optional
            description: Pass true to allow access to all service plans.
        - name: plan_ids
          list:
            computed_optional_required: computed_optional
            description: List of service plan IDs allowed access.
            element_type:
              int64: {}
  moves:
    - namespace: ""
    - template-tenantIds: tenant_ids
    - template-resourcePermissions: resource_permissions
  removes:
    - external_id
    - permissions
    - region_code
    - status
    - success
  overrides:
    active:
      computed_optional_required: computed_optional
      description: Whether the namespace is active.
      default: true
      state_for_unknown: true
    cluster_id:
      computed_optional_required: required
      description: The ID of the cluster.
      requires_replace: true
    description:
      computed_optional_required: optional
      description: The description of the namespace.
    id:
      computed_optional_required: computed
      description: The ID of the cluster namespace.
      state_for_unknown: true
    name:
      computed_optional_required: required
      description: The name of the namespace. Must be 63 characters or less. Must be lower case.
      string_length_at_most: 63
      requires_replace: true
      validators:
        - custom:
            imports:
              - path: github.com/HPE/terraform-provider-hpe/utils/validators
            schema_definition: validators.Lowercase()
    visibility:
      computed_optional_required: computed_optional
      description: The visibility of the cluster namespace (public or private).
      default: "private"
      one_of: [public, private]
      state_for_unknown: true
