vdi_gateway:
  description: "Manages a Morpheus VDI Gateway resource."
  moves:
    - vdi_gateway: ""
  removes:
    - anyof0
    - anyof1
    - api_key
    - date_created
    - last_updated
    - oneof0
  overrides:
    description:
      computed_optional_required: optional
      description: The description of the VDI gateway.
      string_length_at_most: 255
    gateway_url:
      computed_optional_required: optional
      description: The URL of the VDI gateway.
    id:
      computed_optional_required: computed
      description: The ID of the VDI gateway.
      state_for_unknown: true
    name:
      computed_optional_required: required
      description: The name of the VDI gateway.
