cluster_layout:
  moves:
    - layout: "" # unnest wrapper
  removes:
    - actions # nested array
    - compute_servers # nested array of compute-server-type objects
    - environment_variables # nested array
    - group_type # nested object
    - option_types # nested array of option-type objects
    - provision_type # nested object
    - spec_templates # nested array
    - task_sets # nested array
    - type # nested object
  overrides:
    id:
      description: The ID of the cluster layout
      conflicts_with: ["name"]
      computed_optional_required: computed_optional
    name:
      description: The name of the cluster layout
      conflicts_with: ["id"]
      computed_optional_required: computed_optional
    code:
      description: The code identifier of the cluster layout
    description:
      description: A description of the cluster layout
    cluster_version:
      description: The cluster version associated with the layout
    compute_version:
      description: The compute version associated with the layout
    creatable:
      description: Whether clusters of this layout can be created
    enabled:
      description: Whether this cluster layout is enabled
    has_auto_scale:
      description: Whether the layout supports auto scaling
    has_config:
      description: Whether the layout has additional configuration
    has_settings:
      description: Whether the layout has additional settings
    install_container_runtime:
      description: Whether the container runtime is installed by this layout
    internal_id:
      description: The internal identifier of the cluster layout
    memory_requirement:
      description: The memory requirement (in bytes) for this layout
    server_count:
      description: The number of servers defined by this layout
    sort_order:
      description: The display order of the layout
    labels:
      description: Labels associated with the cluster layout
    date_created:
      description: The date the cluster layout was created
    last_updated:
      description: The date the cluster layout was last updated
