// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package clusternamespace

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ClusterNamespaceDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cluster_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the parent cluster.",
				MarkdownDescription: "The ID of the parent cluster.",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the namespace.",
				MarkdownDescription: "The description of the namespace.",
			},
			"external_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The external ID of the namespace.",
				MarkdownDescription: "The external ID of the namespace.",
			},
			"id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The ID of the cluster namespace.",
				MarkdownDescription: "The ID of the cluster namespace.",
				Validators: []validator.Int64{
					int64validator.ConflictsWith(path.Expressions{path.MatchRoot("name")}...),
				},
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the cluster namespace.",
				MarkdownDescription: "The name of the cluster namespace.",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.Expressions{path.MatchRoot("id")}...),
				},
			},
			"visibility": schema.StringAttribute{
				Computed:            true,
				Description:         "The visibility setting for the namespace.",
				MarkdownDescription: "The visibility setting for the namespace.",
			},
		},
	}
}

type ClusterNamespaceModel struct {
	ClusterId   types.Int64  `tfsdk:"cluster_id"`
	Description types.String `tfsdk:"description"`
	ExternalId  types.String `tfsdk:"external_id"`
	Id          types.Int64  `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Visibility  types.String `tfsdk:"visibility"`
}
