backup:
  moves:
    - backup: ""
    - server: host
  overrides:
    id:
      description: ID of the Backup
      conflicts_with: ["name"]
      computed_optional_required: computed_optional
    name:
      string_length_at_least: 1
      description: Name of the Backup. Must not be empty.
      conflicts_with: ["id"]
      computed_optional_required: computed_optional
    host.id:
      description: Host (server) ID
    host.name:
      description: Host (server) name
