// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package computeserver

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ComputeServerDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"agent_installed": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the Morpheus agent is installed on this compute server.",
				MarkdownDescription: "Whether the Morpheus agent is installed on this compute server.",
			},
			"cloud_id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the cloud this compute server belongs to.",
				MarkdownDescription: "The ID of the cloud this compute server belongs to.",
			},
			"cloud_name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the cloud this compute server belongs to.",
				MarkdownDescription: "The name of the cloud this compute server belongs to.",
			},
			"compute_server_type_code": schema.StringAttribute{
				Computed:            true,
				Description:         "The code of the compute server type.",
				MarkdownDescription: "The code of the compute server type.",
			},
			"compute_server_type_id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the compute server type.",
				MarkdownDescription: "The ID of the compute server type.",
			},
			"compute_server_type_managed": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the compute server type is managed.",
				MarkdownDescription: "Whether the compute server type is managed.",
			},
			"compute_server_type_name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the compute server type.",
				MarkdownDescription: "The name of the compute server type.",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the compute server.",
				MarkdownDescription: "The description of the compute server.",
			},
			"external_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The external ID of the compute server.",
				MarkdownDescription: "The external ID of the compute server.",
			},
			"external_ip": schema.StringAttribute{
				Computed:            true,
				Description:         "The external IP address of the compute server.",
				MarkdownDescription: "The external IP address of the compute server.",
			},
			"group_id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the group this compute server belongs to.",
				MarkdownDescription: "The ID of the group this compute server belongs to.",
			},
			"hostname": schema.StringAttribute{
				Computed:            true,
				Description:         "The hostname of the compute server.",
				MarkdownDescription: "The hostname of the compute server.",
			},
			"id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The ID of the compute server. Conflicts with name.",
				MarkdownDescription: "The ID of the compute server. Conflicts with name.",
				Validators: []validator.Int64{
					int64validator.ConflictsWith(path.Expressions{path.MatchRoot("name")}...),
				},
			},
			"instance_id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the instance associated with this compute server, if any.",
				MarkdownDescription: "The ID of the instance associated with this compute server, if any.",
			},
			"internal_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The internal ID of the compute server.",
				MarkdownDescription: "The internal ID of the compute server.",
			},
			"internal_ip": schema.StringAttribute{
				Computed:            true,
				Description:         "The internal IP address of the compute server.",
				MarkdownDescription: "The internal IP address of the compute server.",
			},
			"labels": schema.SetAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "The labels associated with the compute server.",
				MarkdownDescription: "The labels associated with the compute server.",
			},
			"max_memory": schema.Int64Attribute{
				Computed:            true,
				Description:         "The maximum memory allocated to the compute server in bytes.",
				MarkdownDescription: "The maximum memory allocated to the compute server in bytes.",
			},
			"max_storage": schema.Int64Attribute{
				Computed:            true,
				Description:         "The maximum storage allocated to the compute server in bytes.",
				MarkdownDescription: "The maximum storage allocated to the compute server in bytes.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the compute server. Conflicts with id.",
				MarkdownDescription: "The name of the compute server. Conflicts with id.",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.Expressions{path.MatchRoot("id")}...),
				},
			},
			"plan_code": schema.StringAttribute{
				Computed:            true,
				Description:         "The code of the service plan.",
				MarkdownDescription: "The code of the service plan.",
			},
			"plan_id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the service plan.",
				MarkdownDescription: "The ID of the service plan.",
			},
			"plan_name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the service plan.",
				MarkdownDescription: "The name of the service plan.",
			},
			"platform": schema.StringAttribute{
				Computed:            true,
				Description:         "The platform of the compute server (e.g. linux, windows).",
				MarkdownDescription: "The platform of the compute server (e.g. linux, windows).",
			},
			"power_state": schema.StringAttribute{
				Computed:            true,
				Description:         "The power state of the compute server (e.g. on, off).",
				MarkdownDescription: "The power state of the compute server (e.g. on, off).",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "The status of the compute server (e.g. provisioned, running).",
				MarkdownDescription: "The status of the compute server (e.g. provisioned, running).",
			},
			"uuid": schema.StringAttribute{
				Computed:            true,
				Description:         "The UUID of the compute server.",
				MarkdownDescription: "The UUID of the compute server.",
			},
			"visibility": schema.StringAttribute{
				Computed:            true,
				Description:         "The visibility of the compute server (public or private).",
				MarkdownDescription: "The visibility of the compute server (public or private).",
			},
		},
	}
}

type ComputeServerModel struct {
	AgentInstalled           types.Bool   `tfsdk:"agent_installed"`
	CloudId                  types.Int64  `tfsdk:"cloud_id"`
	CloudName                types.String `tfsdk:"cloud_name"`
	ComputeServerTypeCode    types.String `tfsdk:"compute_server_type_code"`
	ComputeServerTypeId      types.Int64  `tfsdk:"compute_server_type_id"`
	ComputeServerTypeManaged types.Bool   `tfsdk:"compute_server_type_managed"`
	ComputeServerTypeName    types.String `tfsdk:"compute_server_type_name"`
	Description              types.String `tfsdk:"description"`
	ExternalId               types.String `tfsdk:"external_id"`
	ExternalIp               types.String `tfsdk:"external_ip"`
	GroupId                  types.Int64  `tfsdk:"group_id"`
	Hostname                 types.String `tfsdk:"hostname"`
	Id                       types.Int64  `tfsdk:"id"`
	InstanceId               types.Int64  `tfsdk:"instance_id"`
	InternalId               types.String `tfsdk:"internal_id"`
	InternalIp               types.String `tfsdk:"internal_ip"`
	Labels                   types.Set    `tfsdk:"labels"`
	MaxMemory                types.Int64  `tfsdk:"max_memory"`
	MaxStorage               types.Int64  `tfsdk:"max_storage"`
	Name                     types.String `tfsdk:"name"`
	PlanCode                 types.String `tfsdk:"plan_code"`
	PlanId                   types.Int64  `tfsdk:"plan_id"`
	PlanName                 types.String `tfsdk:"plan_name"`
	Platform                 types.String `tfsdk:"platform"`
	PowerState               types.String `tfsdk:"power_state"`
	Status                   types.String `tfsdk:"status"`
	Uuid                     types.String `tfsdk:"uuid"`
	Visibility               types.String `tfsdk:"visibility"`
}
