network_router_firewall_rule:
  moves:
    - rule: ""                           # unnest wrapper (components/schemas/networkRouterFirewallRule.yaml)
  removes:
    - applications                       # (components/schemas/networkRouterFirewallRule.yaml) complex nested array
    - destination                        # (components/schemas/networkRouterFirewallRule.yaml) freeform string array
    - profiles                           # (components/schemas/networkRouterFirewallRule.yaml) complex nested array
    - source                             # (components/schemas/networkRouterFirewallRule.yaml) freeform string array
  overrides:
    id:
      computed_optional_required: computed_optional
      description: The ID of the firewall rule.
      conflicts_with: ["name"]
    name:
      computed_optional_required: computed_optional
      description: The name of the firewall rule.
      conflicts_with: ["id"]
    router_id:
      computed_optional_required: required
      description: The ID of the parent network router.
    application:
      description: The application associated with the rule.
    application_type:
      description: The application type.
    code:
      description: The internal code identifier.
    destination_port_range:
      description: The destination port range.
    destination_type:
      description: The destination type.
    direction:
      description: Direction (ingress or egress).
    enabled:
      description: Whether the firewall rule is enabled.
    group_name:
      description: The group name this rule belongs to.
    policy:
      description: Policy action (accept, block, reject).
    port_range:
      description: Port range.
    priority:
      description: Priority of the firewall rule.
    protocol:
      description: Protocol.
    rule_type:
      description: The type of the firewall rule.
    source_group:
      description: The source group.
    source_port_range:
      description: The source port range.
    source_tier:
      description: The source tier.
    source_type:
      description: The source type.
