// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package monitoring_check

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func MonitoringCheckResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"active": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether the check is active.",
				MarkdownDescription: "Whether the check is active.",
				Default:             booldefault.StaticBool(true),
			},
			"check_interval": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Check interval in seconds.",
				MarkdownDescription: "Check interval in seconds.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
				Default: int64default.StaticInt64(300),
			},
			"check_type_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The check type ID.",
				MarkdownDescription: "The check type ID.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Description:         "The description of the monitoring check.",
				MarkdownDescription: "The description of the monitoring check.",
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the monitoring check.",
				MarkdownDescription: "The ID of the monitoring check.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"in_uptime": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether the check affects account-wide availability calculations.",
				MarkdownDescription: "Whether the check affects account-wide availability calculations.",
				Default:             booldefault.StaticBool(true),
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the monitoring check.",
				MarkdownDescription: "The name of the monitoring check.",
			},
			"severity": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Severity level threshold for sending notifications.",
				MarkdownDescription: "Severity level threshold for sending notifications.",
				Default:             stringdefault.StaticString("critical"),
			},
		},
		Description:         "Manages a Morpheus Monitoring Check resource.",
		MarkdownDescription: "Manages a Morpheus Monitoring Check resource.",
	}
}

type MonitoringCheckModel struct {
	Active        types.Bool   `tfsdk:"active"`
	CheckInterval types.Int64  `tfsdk:"check_interval"`
	CheckTypeId   types.Int64  `tfsdk:"check_type_id"`
	Description   types.String `tfsdk:"description"`
	Id            types.Int64  `tfsdk:"id"`
	InUptime      types.Bool   `tfsdk:"in_uptime"`
	Name          types.String `tfsdk:"name"`
	Severity      types.String `tfsdk:"severity"`
}
