// (C) Copyright 2026 Hewlett Packard Enterprise Development LP

package sweep

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"regexp"
	"strconv"
	"strings"

	"github.com/HewlettPackard/hpe-morpheus-go-sdk/oapigen/sdk"

	testsweep "github.com/HPE/terraform-provider-hpe/morpheus/testhelpers/sweep"
	"github.com/HPE/terraform-provider-hpe/morpheus/utils/errfmt"
)

// lbTestInstanceNameRe matches the names generated by load balancer acceptance
// tests: acctest.RandomWithPrefix(t.Name()) truncated to first 16 + last 16
// characters, producing "TestAccMorpheusL" followed by 16 digits (total 32).
var lbTestInstanceNameRe = regexp.MustCompile(`^TestAccMorpheusL\d{16}$`)

func init() {
	testsweep.RegisterTypedAPISweeper(
		"hpe_morpheus_load_balancer",
		// List all load balancer resources. As a side-effect, also sweep orphaned
		// Docker container instances — HAProxy load balancers provision instances
		// on Docker clusters that are not automatically removed when the load
		// balancer is deleted.
		func(ctx context.Context, client *sdk.APIClient) (
			[]sdk.ListLoadBalancers200ResponseAllOfLoadBalancersInner,
			*http.Response,
			error,
		) {
			sweepOrphanedInstances(ctx, client)

			resp, hresp, err := client.LoadBalancersAPI.ListLoadBalancers(ctx).Execute()
			if resp == nil {
				return nil, hresp, err
			}

			return resp.GetLoadBalancers(), hresp, err
		},
		// Is this a test load balancer?
		func(item sdk.ListLoadBalancers200ResponseAllOfLoadBalancersInner) bool {
			name, ok := item.GetNameOk()
			if !ok || name == nil {
				return false
			}

			return strings.HasPrefix(*name, testsweep.TestResourcePrefix)
		},
		// Delete the test load balancer.
		func(
			ctx context.Context,
			client *sdk.APIClient,
			item sdk.ListLoadBalancers200ResponseAllOfLoadBalancersInner,
		) (*http.Response, error) {
			id, ok := item.GetIdOk()
			if !ok || id == nil {
				return nil, fmt.Errorf("could not get ID")
			}

			_, hresp, err := client.LoadBalancersAPI.DeleteLoadBalancer(ctx, *id).Execute()

			return hresp, err
		},
	)
}

// sweepOrphanedInstances removes test-prefixed instances that were provisioned
// by HAProxy load balancers on Docker clusters. These instances represent the
// actual Docker containers and are not automatically cleaned up when the load
// balancer is deleted. The instances are hidden from the standard ListInstances
// API, so the Search API is used to discover them.
func sweepOrphanedInstances(ctx context.Context, client *sdk.APIClient) {
	var (
		offset   int64
		sweptCnt int
		errCnt   int
	)

	const pageSize int64 = 100

	for {
		resp, hresp, err := client.SearchAPI.Search(ctx).
			Phrase(testsweep.TestResourcePrefix).
			Max(pageSize).
			Offset(offset).
			Execute()
		if err != nil {
			log.Printf("[ERROR] Failed to search for orphaned instances: %s", errfmt.ErrMsg(err, hresp))

			return
		}

		hits := resp.GetHits()

		for i := range hits {
			swept, errored := sweepHitIfInstance(ctx, client, &hits[i])
			sweptCnt += swept
			errCnt += errored
		}

		meta, ok := resp.GetMetaOk()
		if !ok || meta == nil {
			break
		}

		offset += int64(len(hits))
		if offset >= meta.GetTotal() {
			break
		}
	}

	log.Printf(
		"[INFO] Instance sweep completed. Instances swept: %d, errors: %d",
		sweptCnt, errCnt,
	)
}

// sweepHitIfInstance deletes a search hit if it is a test-prefixed Instance.
// Returns (1, 0) on success, (0, 1) on error, and (0, 0) if the hit is not
// an applicable instance.
func sweepHitIfInstance(
	ctx context.Context,
	client *sdk.APIClient,
	hit *sdk.Search200ResponseHitsInner,
) (swept, errored int) {
	hitType, ok := hit.GetTypeOk()
	if !ok || hitType == nil || *hitType != "Instance" {
		return 0, 0
	}

	name, ok := hit.GetNameOk()
	if !ok || name == nil || !lbTestInstanceNameRe.MatchString(*name) {
		return 0, 0
	}

	idStr, ok := hit.GetIdOk()
	if !ok || idStr == nil {
		return 0, 0
	}

	id, err := strconv.ParseInt(*idStr, 10, 64)
	if err != nil {
		log.Printf("[ERROR] Failed to parse instance ID %q: %v", *idStr, err)

		return 0, 1
	}

	log.Printf("[INFO] Sweeping orphaned instance %q (id=%d)", *name, id)

	_, delResp, delErr := client.InstancesAPI.
		DeleteInstance(ctx, id).
		Force("on").
		Execute()
	if delErr != nil {
		if delResp != nil && delResp.StatusCode == http.StatusNotFound {
			log.Printf("[INFO] Instance %q already removed (404)", *name)

			return 0, 0
		}

		log.Printf("[ERROR] Failed to delete instance %q (id=%d): %s",
			*name, id, errfmt.ErrMsg(delErr, delResp))

		return 0, 1
	}

	return 1, 0
}
