// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package networkrouterfirewallrulegroup

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func NetworkRouterFirewallRuleGroupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Network router firewall rule group description",
				MarkdownDescription: "Network router firewall rule group description",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"external_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The external ID of the firewall rule group as assigned by the network\nprovider (e.g. \"Policy_Default_Infra-tier1-a2fd5aac-2370-4607-9894-0b0a18dd94c0\" for NSX-T). Use this as the parent_id when\ncreating hpe_morpheus_network_router_firewall_rule resources.",
				MarkdownDescription: "The external ID of the firewall rule group as assigned by the network\nprovider (e.g. \"Policy_Default_Infra-tier1-a2fd5aac-2370-4607-9894-0b0a18dd94c0\" for NSX-T). Use this as the parent_id when\ncreating hpe_morpheus_network_router_firewall_rule resources.",
			},
			"group_layer": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The NSX-T gateway firewall policy category. Valid values: Emergency,\nSharedPreRules (Pre Rules), LocalGatewayRules (Local Gateway).\nSystem-managed categories (SystemRules, AutoServiceRules, Default)\ncannot be created via the API.",
				MarkdownDescription: "The NSX-T gateway firewall policy category. Valid values: Emergency,\nSharedPreRules (Pre Rules), LocalGatewayRules (Local Gateway).\nSystem-managed categories (SystemRules, AutoServiceRules, Default)\ncannot be created via the API.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("Emergency", "SharedPreRules", "LocalGatewayRules"),
				},
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the firewall rule group",
				MarkdownDescription: "The ID of the firewall rule group",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Network router firewall rule group name",
				MarkdownDescription: "Network router firewall rule group name",
			},
			"priority": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Network router firewall rule group priority",
				MarkdownDescription: "Network router firewall rule group priority",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"router_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the parent network router",
				MarkdownDescription: "The ID of the parent network router",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "The current status of the firewall rule group",
				MarkdownDescription: "The current status of the firewall rule group",
			},
			"tenant_ids": schema.SetAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Description:         "List of tenant account IDs that are allowed access to this firewall rule\ngroup. Only configurable from a master tenant account. Note: the API does\nnot return this field on individual GET responses; the configured value is\npreserved in state and will be null after import.",
				MarkdownDescription: "List of tenant account IDs that are allowed access to this firewall rule\ngroup. Only configurable from a master tenant account. Note: the API does\nnot return this field on individual GET responses; the configured value is\npreserved in state and will be null after import.",
			},
			"visibility": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The visibility of the firewall rule group (public or private). Note: the API\ndoes not return this field on individual GET responses; the configured value\nis preserved in state and will be null after import.",
				MarkdownDescription: "The visibility of the firewall rule group (public or private). Note: the API\ndoes not return this field on individual GET responses; the configured value\nis preserved in state and will be null after import.",
				Validators: []validator.String{
					stringvalidator.OneOf("public", "private"),
				},
				Default: stringdefault.StaticString("private"),
			},
		},
		Description:         "Manages an NSX-T gateway firewall policy group in Morpheus. Gateway firewall\npolicies are attached to a specific Tier-0 or Tier-1 router and control\nnorth-south traffic traversing that gateway. The external type is fixed as\nGatewayPolicy; for east-west distributed firewall policies, use\nhpe_morpheus_network_firewall_rule_group instead.",
		MarkdownDescription: "Manages an NSX-T gateway firewall policy group in Morpheus. Gateway firewall\npolicies are attached to a specific Tier-0 or Tier-1 router and control\nnorth-south traffic traversing that gateway. The external type is fixed as\nGatewayPolicy; for east-west distributed firewall policies, use\nhpe_morpheus_network_firewall_rule_group instead.",
	}
}

type NetworkRouterFirewallRuleGroupModel struct {
	Description types.String `tfsdk:"description"`
	ExternalId  types.String `tfsdk:"external_id"`
	GroupLayer  types.String `tfsdk:"group_layer"`
	Id          types.Int64  `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Priority    types.Int64  `tfsdk:"priority"`
	RouterId    types.Int64  `tfsdk:"router_id"`
	Status      types.String `tfsdk:"status"`
	TenantIds   types.Set    `tfsdk:"tenant_ids"`
	Visibility  types.String `tfsdk:"visibility"`
}
