// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package loadbalancerpool

import (
	"context"
	"fmt"
	"github.com/HPE/terraform-provider-hpe/utils/validators"
	"github.com/hashicorp/terraform-plugin-framework-validators/dynamicvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func LoadBalancerPoolResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allow_nat": schema.StringAttribute{
				Computed: true,
			},
			"allow_snat": schema.StringAttribute{
				Computed: true,
			},
			"category": schema.StringAttribute{
				Computed: true,
			},
			"config": schema.DynamicAttribute{
				Optional:            true,
				Description:         "Generic pool configuration object. Settings vary by load balancer type.",
				MarkdownDescription: "Generic pool configuration object. Settings vary by load balancer type.",
				Validators: []validator.Dynamic{
					validators.ValidObjectMap(),
					dynamicvalidator.ConflictsWith(path.Expressions{path.MatchRoot("config_nsxt")}...),
				},
			},
			"config_nsxt": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"active_monitor_paths": schema.Int64Attribute{
						Optional:            true,
						Computed:            true,
						Description:         "The ID of the active health monitor (NetworkLoadBalancerMonitor).\nThe Options API `/api/options/nsxt/nsxtLBPoolActiveMonitor?loadBalancerId={id}` can be used to see which options are available.",
						MarkdownDescription: "The ID of the active health monitor (NetworkLoadBalancerMonitor).\nThe Options API `/api/options/nsxt/nsxtLBPoolActiveMonitor?loadBalancerId={id}` can be used to see which options are available.",
					},
					"member_group": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"ip_revision_filter": schema.StringAttribute{
								Optional:            true,
								Computed:            true,
								Description:         "IP revision filter for the member group.",
								MarkdownDescription: "IP revision filter for the member group.",
								Validators: []validator.String{
									stringvalidator.OneOf(
										"IPV4",
										"IPV6",
										"IPV4_IPV6",
									),
								},
							},
							"max_ip_list_size": schema.Int64Attribute{
								Optional:            true,
								Computed:            true,
								Description:         "Maximum IP list size for the member group.",
								MarkdownDescription: "Maximum IP list size for the member group.",
							},
							"path": schema.StringAttribute{
								Optional:            true,
								Computed:            true,
								Description:         "NSX-T member group path.",
								MarkdownDescription: "NSX-T member group path.",
							},
							"port": schema.Int64Attribute{
								Optional:            true,
								Computed:            true,
								Description:         "Port number for the member group.",
								MarkdownDescription: "Port number for the member group.",
							},
						},
						CustomType: MemberGroupType{
							ObjectType: types.ObjectType{
								AttrTypes: MemberGroupValue{}.AttributeTypes(ctx),
							},
						},
						Optional:            true,
						Computed:            true,
						Description:         "NSX-T member group configuration. When set, pool membership is determined by group membership instead of explicit nodes.",
						MarkdownDescription: "NSX-T member group configuration. When set, pool membership is determined by group membership instead of explicit nodes.",
					},
					"passive_monitor_path": schema.Int64Attribute{
						Optional:            true,
						Computed:            true,
						Description:         "The ID of the passive health monitor (NetworkLoadBalancerMonitor).\nThe Options API `/api/options/nsxt/nsxtLBPoolPassiveMonitor?loadBalancerId={id}` can be used to see which options are available.",
						MarkdownDescription: "The ID of the passive health monitor (NetworkLoadBalancerMonitor).\nThe Options API `/api/options/nsxt/nsxtLBPoolPassiveMonitor?loadBalancerId={id}` can be used to see which options are available.",
					},
					"snat_ip_addresses": schema.SetAttribute{
						ElementType:         types.StringType,
						Optional:            true,
						Computed:            true,
						Description:         "List of SNAT IP addresses. Required when snatTranslationType is LBSnatIpPool.",
						MarkdownDescription: "List of SNAT IP addresses. Required when snatTranslationType is LBSnatIpPool.",
					},
					"snat_translation_type": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "SNAT translation type. Determines how source NAT is applied to pool traffic.",
						MarkdownDescription: "SNAT translation type. Determines how source NAT is applied to pool traffic.",
						Validators: []validator.String{
							stringvalidator.OneOf(
								"LBSnatDisabled",
								"LBSnatAutoMap",
								"LBSnatIpPool",
							),
						},
					},
					"tcp_multiplexing": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Whether TCP multiplexing is enabled for the pool.",
						MarkdownDescription: "Whether TCP multiplexing is enabled for the pool.",
					},
					"tcp_multiplexing_number": schema.Int64Attribute{
						Optional:            true,
						Computed:            true,
						Description:         "Maximum number of TCP multiplexing connections. Defaults to 6.",
						MarkdownDescription: "Maximum number of TCP multiplexing connections. Defaults to 6.",
					},
				},
				CustomType: ConfigNsxtType{
					ObjectType: types.ObjectType{
						AttrTypes: ConfigNsxtValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Configuration object for NSX-T load balancer pool type.",
				MarkdownDescription: "Configuration object for NSX-T load balancer pool type.",
				Validators: []validator.Object{
					objectvalidator.ConflictsWith(path.Expressions{path.MatchRoot("config")}...),
				},
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A description of the load balancer pool",
				MarkdownDescription: "A description of the load balancer pool",
			},
			"down_action": schema.StringAttribute{
				Computed: true,
			},
			"enabled": schema.BoolAttribute{
				Computed: true,
			},
			"error_penalty": schema.Int64Attribute{
				Computed: true,
			},
			"external_id": schema.StringAttribute{
				Computed: true,
			},
			"health_penalty": schema.Int64Attribute{
				Computed: true,
			},
			"health_score": schema.Int64Attribute{
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"internal_id": schema.StringAttribute{
				Computed: true,
			},
			"last_updated": schema.StringAttribute{
				Computed: true,
			},
			"load_balancer": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.Int64Attribute{
						Computed: true,
					},
					"ip": schema.StringAttribute{
						Computed: true,
					},
					"name": schema.StringAttribute{
						Computed: true,
					},
					"type": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"code": schema.StringAttribute{
								Computed: true,
							},
							"id": schema.Int64Attribute{
								Computed: true,
							},
							"name": schema.StringAttribute{
								Computed: true,
							},
						},
						CustomType: TypeType{
							ObjectType: types.ObjectType{
								AttrTypes: TypeValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
				},
				CustomType: LoadBalancerType{
					ObjectType: types.ObjectType{
						AttrTypes: LoadBalancerValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"load_balancer_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the load balancer this pool belongs to",
				MarkdownDescription: "The ID of the load balancer this pool belongs to",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"max_queue_depth": schema.StringAttribute{
				Computed: true,
			},
			"max_queue_time": schema.StringAttribute{
				Computed: true,
			},
			"min_active": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Minimum number of active pool members",
				MarkdownDescription: "Minimum number of active pool members",
			},
			"min_in_service": schema.StringAttribute{
				Computed: true,
			},
			"min_up_action": schema.StringAttribute{
				Computed: true,
			},
			"min_up_monitor": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the load balancer pool",
				MarkdownDescription: "The name of the load balancer pool",
			},
			"number_active": schema.Int64Attribute{
				Computed: true,
			},
			"number_in_service": schema.Int64Attribute{
				Computed: true,
			},
			"partition": schema.StringAttribute{
				Optional:            true,
				WriteOnly:           true,
				Description:         "Partition identifier",
				MarkdownDescription: "Partition identifier",
			},
			"performance_score": schema.Int64Attribute{
				Computed: true,
			},
			"port": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The port number for the pool",
				MarkdownDescription: "The port number for the pool",
			},
			"port_type": schema.StringAttribute{
				Computed: true,
			},
			"ramp_time": schema.StringAttribute{
				Computed: true,
			},
			"security_penalty": schema.Int64Attribute{
				Computed: true,
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
			"vip_balance": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The balance algorithm for the pool (e.g. ROUND_ROBIN, LEAST_CONNECTION, IP_HASH)",
				MarkdownDescription: "The balance algorithm for the pool (e.g. ROUND_ROBIN, LEAST_CONNECTION, IP_HASH)",
			},
			"vip_client_ip_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "VIP client IP mode",
				MarkdownDescription: "VIP client IP mode",
			},
			"vip_server_ip_mode": schema.StringAttribute{
				Computed: true,
			},
			"vip_sticky": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Session persistence mode for the pool",
				MarkdownDescription: "Session persistence mode for the pool",
			},
			"visibility": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type LoadBalancerPoolModel struct {
	AllowNat         types.String      `tfsdk:"allow_nat"`
	AllowSnat        types.String      `tfsdk:"allow_snat"`
	Category         types.String      `tfsdk:"category"`
	Config           types.Dynamic     `tfsdk:"config"`
	ConfigNsxt       ConfigNsxtValue   `tfsdk:"config_nsxt"`
	Description      types.String      `tfsdk:"description"`
	DownAction       types.String      `tfsdk:"down_action"`
	Enabled          types.Bool        `tfsdk:"enabled"`
	ErrorPenalty     types.Int64       `tfsdk:"error_penalty"`
	ExternalId       types.String      `tfsdk:"external_id"`
	HealthPenalty    types.Int64       `tfsdk:"health_penalty"`
	HealthScore      types.Int64       `tfsdk:"health_score"`
	Id               types.Int64       `tfsdk:"id"`
	InternalId       types.String      `tfsdk:"internal_id"`
	LastUpdated      types.String      `tfsdk:"last_updated"`
	LoadBalancer     LoadBalancerValue `tfsdk:"load_balancer"`
	LoadBalancerId   types.Int64       `tfsdk:"load_balancer_id"`
	MaxQueueDepth    types.String      `tfsdk:"max_queue_depth"`
	MaxQueueTime     types.String      `tfsdk:"max_queue_time"`
	MinActive        types.Int64       `tfsdk:"min_active"`
	MinInService     types.String      `tfsdk:"min_in_service"`
	MinUpAction      types.String      `tfsdk:"min_up_action"`
	MinUpMonitor     types.String      `tfsdk:"min_up_monitor"`
	Name             types.String      `tfsdk:"name"`
	NumberActive     types.Int64       `tfsdk:"number_active"`
	NumberInService  types.Int64       `tfsdk:"number_in_service"`
	Partition        types.String      `tfsdk:"partition"`
	PerformanceScore types.Int64       `tfsdk:"performance_score"`
	Port             types.Int64       `tfsdk:"port"`
	PortType         types.String      `tfsdk:"port_type"`
	RampTime         types.String      `tfsdk:"ramp_time"`
	SecurityPenalty  types.Int64       `tfsdk:"security_penalty"`
	Status           types.String      `tfsdk:"status"`
	VipBalance       types.String      `tfsdk:"vip_balance"`
	VipClientIpMode  types.String      `tfsdk:"vip_client_ip_mode"`
	VipServerIpMode  types.String      `tfsdk:"vip_server_ip_mode"`
	VipSticky        types.String      `tfsdk:"vip_sticky"`
	Visibility       types.String      `tfsdk:"visibility"`
}

var _ basetypes.ObjectTypable = ConfigNsxtType{}

type ConfigNsxtType struct {
	basetypes.ObjectType
}

func (t ConfigNsxtType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigNsxtType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigNsxtType) String() string {
	return "ConfigNsxtType"
}

func (t ConfigNsxtType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewConfigNsxtValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtValueNull(), nil
	}

	attributes := in.Attributes()

	activeMonitorPathsAttribute, ok := attributes["active_monitor_paths"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`active_monitor_paths is missing from object`)

		return nil, diags
	}

	activeMonitorPathsVal, ok := activeMonitorPathsAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`active_monitor_paths expected to be basetypes.Int64Value, was: %T`, activeMonitorPathsAttribute))
	}

	memberGroupAttribute, ok := attributes["member_group"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`member_group is missing from object`)

		return nil, diags
	}

	memberGroupVal, ok := memberGroupAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`member_group expected to be basetypes.ObjectValue, was: %T`, memberGroupAttribute))
	}

	passiveMonitorPathAttribute, ok := attributes["passive_monitor_path"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`passive_monitor_path is missing from object`)

		return nil, diags
	}

	passiveMonitorPathVal, ok := passiveMonitorPathAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`passive_monitor_path expected to be basetypes.Int64Value, was: %T`, passiveMonitorPathAttribute))
	}

	snatIpAddressesAttribute, ok := attributes["snat_ip_addresses"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`snat_ip_addresses is missing from object`)

		return nil, diags
	}

	snatIpAddressesVal, ok := snatIpAddressesAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`snat_ip_addresses expected to be basetypes.SetValue, was: %T`, snatIpAddressesAttribute))
	}

	snatTranslationTypeAttribute, ok := attributes["snat_translation_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`snat_translation_type is missing from object`)

		return nil, diags
	}

	snatTranslationTypeVal, ok := snatTranslationTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`snat_translation_type expected to be basetypes.StringValue, was: %T`, snatTranslationTypeAttribute))
	}

	tcpMultiplexingAttribute, ok := attributes["tcp_multiplexing"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tcp_multiplexing is missing from object`)

		return nil, diags
	}

	tcpMultiplexingVal, ok := tcpMultiplexingAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tcp_multiplexing expected to be basetypes.BoolValue, was: %T`, tcpMultiplexingAttribute))
	}

	tcpMultiplexingNumberAttribute, ok := attributes["tcp_multiplexing_number"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tcp_multiplexing_number is missing from object`)

		return nil, diags
	}

	tcpMultiplexingNumberVal, ok := tcpMultiplexingNumberAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tcp_multiplexing_number expected to be basetypes.Int64Value, was: %T`, tcpMultiplexingNumberAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigNsxtValue{
		ActiveMonitorPaths:    activeMonitorPathsVal,
		MemberGroup:           memberGroupVal,
		PassiveMonitorPath:    passiveMonitorPathVal,
		SnatIpAddresses:       snatIpAddressesVal,
		SnatTranslationType:   snatTranslationTypeVal,
		TcpMultiplexing:       tcpMultiplexingVal,
		TcpMultiplexingNumber: tcpMultiplexingNumberVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtValueNull() ConfigNsxtValue {
	return ConfigNsxtValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigNsxtValueUnknown() ConfigNsxtValue {
	return ConfigNsxtValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigNsxtValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigNsxtValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigNsxtValue Attribute Value",
				"While creating a ConfigNsxtValue value, a missing attribute value was detected. "+
					"A ConfigNsxtValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigNsxtValue Attribute Type",
				"While creating a ConfigNsxtValue value, an invalid attribute value was detected. "+
					"A ConfigNsxtValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigNsxtValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigNsxtValue Attribute Value",
				"While creating a ConfigNsxtValue value, an extra attribute value was detected. "+
					"A ConfigNsxtValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigNsxtValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigNsxtValueUnknown(), diags
	}

	activeMonitorPathsAttribute, ok := attributes["active_monitor_paths"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`active_monitor_paths is missing from object`)

		return NewConfigNsxtValueUnknown(), diags
	}

	activeMonitorPathsVal, ok := activeMonitorPathsAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`active_monitor_paths expected to be basetypes.Int64Value, was: %T`, activeMonitorPathsAttribute))
	}

	memberGroupAttribute, ok := attributes["member_group"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`member_group is missing from object`)

		return NewConfigNsxtValueUnknown(), diags
	}

	memberGroupVal, ok := memberGroupAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`member_group expected to be basetypes.ObjectValue, was: %T`, memberGroupAttribute))
	}

	passiveMonitorPathAttribute, ok := attributes["passive_monitor_path"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`passive_monitor_path is missing from object`)

		return NewConfigNsxtValueUnknown(), diags
	}

	passiveMonitorPathVal, ok := passiveMonitorPathAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`passive_monitor_path expected to be basetypes.Int64Value, was: %T`, passiveMonitorPathAttribute))
	}

	snatIpAddressesAttribute, ok := attributes["snat_ip_addresses"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`snat_ip_addresses is missing from object`)

		return NewConfigNsxtValueUnknown(), diags
	}

	snatIpAddressesVal, ok := snatIpAddressesAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`snat_ip_addresses expected to be basetypes.SetValue, was: %T`, snatIpAddressesAttribute))
	}

	snatTranslationTypeAttribute, ok := attributes["snat_translation_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`snat_translation_type is missing from object`)

		return NewConfigNsxtValueUnknown(), diags
	}

	snatTranslationTypeVal, ok := snatTranslationTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`snat_translation_type expected to be basetypes.StringValue, was: %T`, snatTranslationTypeAttribute))
	}

	tcpMultiplexingAttribute, ok := attributes["tcp_multiplexing"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tcp_multiplexing is missing from object`)

		return NewConfigNsxtValueUnknown(), diags
	}

	tcpMultiplexingVal, ok := tcpMultiplexingAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tcp_multiplexing expected to be basetypes.BoolValue, was: %T`, tcpMultiplexingAttribute))
	}

	tcpMultiplexingNumberAttribute, ok := attributes["tcp_multiplexing_number"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tcp_multiplexing_number is missing from object`)

		return NewConfigNsxtValueUnknown(), diags
	}

	tcpMultiplexingNumberVal, ok := tcpMultiplexingNumberAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tcp_multiplexing_number expected to be basetypes.Int64Value, was: %T`, tcpMultiplexingNumberAttribute))
	}

	if diags.HasError() {
		return NewConfigNsxtValueUnknown(), diags
	}

	return ConfigNsxtValue{
		ActiveMonitorPaths:    activeMonitorPathsVal,
		MemberGroup:           memberGroupVal,
		PassiveMonitorPath:    passiveMonitorPathVal,
		SnatIpAddresses:       snatIpAddressesVal,
		SnatTranslationType:   snatTranslationTypeVal,
		TcpMultiplexing:       tcpMultiplexingVal,
		TcpMultiplexingNumber: tcpMultiplexingNumberVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewConfigNsxtValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigNsxtValue {
	object, diags := NewConfigNsxtValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewConfigNsxtValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigNsxtType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigNsxtValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigNsxtValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigNsxtValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigNsxtValueMust(ConfigNsxtValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigNsxtType) ValueType(ctx context.Context) attr.Value {
	return ConfigNsxtValue{}
}

var _ basetypes.ObjectValuable = ConfigNsxtValue{}

type ConfigNsxtValue struct {
	ActiveMonitorPaths    basetypes.Int64Value  `tfsdk:"active_monitor_paths"`
	MemberGroup           basetypes.ObjectValue `tfsdk:"member_group"`
	PassiveMonitorPath    basetypes.Int64Value  `tfsdk:"passive_monitor_path"`
	SnatIpAddresses       basetypes.SetValue    `tfsdk:"snat_ip_addresses"`
	SnatTranslationType   basetypes.StringValue `tfsdk:"snat_translation_type"`
	TcpMultiplexing       basetypes.BoolValue   `tfsdk:"tcp_multiplexing"`
	TcpMultiplexingNumber basetypes.Int64Value  `tfsdk:"tcp_multiplexing_number"`
	state                 attr.ValueState
}

func (v ConfigNsxtValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["active_monitor_paths"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["member_group"] = basetypes.ObjectType{
		AttrTypes: MemberGroupValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["passive_monitor_path"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["snat_ip_addresses"] = basetypes.SetType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["snat_translation_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tcp_multiplexing"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["tcp_multiplexing_number"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.ActiveMonitorPaths.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["active_monitor_paths"] = val

		val, err = v.MemberGroup.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["member_group"] = val

		val, err = v.PassiveMonitorPath.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["passive_monitor_path"] = val

		val, err = v.SnatIpAddresses.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["snat_ip_addresses"] = val

		val, err = v.SnatTranslationType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["snat_translation_type"] = val

		val, err = v.TcpMultiplexing.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tcp_multiplexing"] = val

		val, err = v.TcpMultiplexingNumber.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tcp_multiplexing_number"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigNsxtValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigNsxtValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigNsxtValue) String() string {
	return "ConfigNsxtValue"
}

func (v ConfigNsxtValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var memberGroupVal basetypes.ObjectValue

	if v.MemberGroup.IsNull() {
		memberGroupVal = types.ObjectNull(
			MemberGroupValue{}.AttributeTypes(ctx),
		)
	}

	if v.MemberGroup.IsUnknown() {
		memberGroupVal = types.ObjectUnknown(
			MemberGroupValue{}.AttributeTypes(ctx),
		)
	}

	if !v.MemberGroup.IsNull() && !v.MemberGroup.IsUnknown() {
		memberGroupVal = types.ObjectValueMust(
			MemberGroupValue{}.AttributeTypes(ctx),
			v.MemberGroup.Attributes(),
		)
	}

	var snatIpAddressesVal basetypes.SetValue
	switch {
	case v.SnatIpAddresses.IsUnknown():
		snatIpAddressesVal = types.SetUnknown(types.StringType)
	case v.SnatIpAddresses.IsNull():
		snatIpAddressesVal = types.SetNull(types.StringType)
	default:
		var d diag.Diagnostics
		snatIpAddressesVal, d = types.SetValue(types.StringType, v.SnatIpAddresses.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"active_monitor_paths": basetypes.Int64Type{},
			"member_group": basetypes.ObjectType{
				AttrTypes: MemberGroupValue{}.AttributeTypes(ctx),
			},
			"passive_monitor_path": basetypes.Int64Type{},
			"snat_ip_addresses": basetypes.SetType{
				ElemType: types.StringType,
			},
			"snat_translation_type":   basetypes.StringType{},
			"tcp_multiplexing":        basetypes.BoolType{},
			"tcp_multiplexing_number": basetypes.Int64Type{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"active_monitor_paths": basetypes.Int64Type{},
		"member_group": basetypes.ObjectType{
			AttrTypes: MemberGroupValue{}.AttributeTypes(ctx),
		},
		"passive_monitor_path": basetypes.Int64Type{},
		"snat_ip_addresses": basetypes.SetType{
			ElemType: types.StringType,
		},
		"snat_translation_type":   basetypes.StringType{},
		"tcp_multiplexing":        basetypes.BoolType{},
		"tcp_multiplexing_number": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"active_monitor_paths":    v.ActiveMonitorPaths,
			"member_group":            memberGroupVal,
			"passive_monitor_path":    v.PassiveMonitorPath,
			"snat_ip_addresses":       snatIpAddressesVal,
			"snat_translation_type":   v.SnatTranslationType,
			"tcp_multiplexing":        v.TcpMultiplexing,
			"tcp_multiplexing_number": v.TcpMultiplexingNumber,
		})

	return objVal, diags
}

func (v ConfigNsxtValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigNsxtValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ActiveMonitorPaths.Equal(other.ActiveMonitorPaths) {
		return false
	}

	if !v.MemberGroup.Equal(other.MemberGroup) {
		return false
	}

	if !v.PassiveMonitorPath.Equal(other.PassiveMonitorPath) {
		return false
	}

	if !v.SnatIpAddresses.Equal(other.SnatIpAddresses) {
		return false
	}

	if !v.SnatTranslationType.Equal(other.SnatTranslationType) {
		return false
	}

	if !v.TcpMultiplexing.Equal(other.TcpMultiplexing) {
		return false
	}

	if !v.TcpMultiplexingNumber.Equal(other.TcpMultiplexingNumber) {
		return false
	}

	return true
}

func (v ConfigNsxtValue) Type(ctx context.Context) attr.Type {
	return ConfigNsxtType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigNsxtValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"active_monitor_paths": basetypes.Int64Type{},
		"member_group": basetypes.ObjectType{
			AttrTypes: MemberGroupValue{}.AttributeTypes(ctx),
		},
		"passive_monitor_path": basetypes.Int64Type{},
		"snat_ip_addresses": basetypes.SetType{
			ElemType: types.StringType,
		},
		"snat_translation_type":   basetypes.StringType{},
		"tcp_multiplexing":        basetypes.BoolType{},
		"tcp_multiplexing_number": basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = MemberGroupType{}

type MemberGroupType struct {
	basetypes.ObjectType
}

func (t MemberGroupType) Equal(o attr.Type) bool {
	other, ok := o.(MemberGroupType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MemberGroupType) String() string {
	return "MemberGroupType"
}

func (t MemberGroupType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewMemberGroupValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMemberGroupValueNull(), nil
	}

	attributes := in.Attributes()

	ipRevisionFilterAttribute, ok := attributes["ip_revision_filter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_revision_filter is missing from object`)

		return nil, diags
	}

	ipRevisionFilterVal, ok := ipRevisionFilterAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_revision_filter expected to be basetypes.StringValue, was: %T`, ipRevisionFilterAttribute))
	}

	maxIpListSizeAttribute, ok := attributes["max_ip_list_size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_ip_list_size is missing from object`)

		return nil, diags
	}

	maxIpListSizeVal, ok := maxIpListSizeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_ip_list_size expected to be basetypes.Int64Value, was: %T`, maxIpListSizeAttribute))
	}

	pathAttribute, ok := attributes["path"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`path is missing from object`)

		return nil, diags
	}

	pathVal, ok := pathAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`path expected to be basetypes.StringValue, was: %T`, pathAttribute))
	}

	portAttribute, ok := attributes["port"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`port is missing from object`)

		return nil, diags
	}

	portVal, ok := portAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`port expected to be basetypes.Int64Value, was: %T`, portAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MemberGroupValue{
		IpRevisionFilter: ipRevisionFilterVal,
		MaxIpListSize:    maxIpListSizeVal,
		Path:             pathVal,
		Port:             portVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewMemberGroupValueNull() MemberGroupValue {
	return MemberGroupValue{
		state: attr.ValueStateNull,
	}
}

func NewMemberGroupValueUnknown() MemberGroupValue {
	return MemberGroupValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMemberGroupValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MemberGroupValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MemberGroupValue Attribute Value",
				"While creating a MemberGroupValue value, a missing attribute value was detected. "+
					"A MemberGroupValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MemberGroupValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MemberGroupValue Attribute Type",
				"While creating a MemberGroupValue value, an invalid attribute value was detected. "+
					"A MemberGroupValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MemberGroupValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MemberGroupValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MemberGroupValue Attribute Value",
				"While creating a MemberGroupValue value, an extra attribute value was detected. "+
					"A MemberGroupValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MemberGroupValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMemberGroupValueUnknown(), diags
	}

	ipRevisionFilterAttribute, ok := attributes["ip_revision_filter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_revision_filter is missing from object`)

		return NewMemberGroupValueUnknown(), diags
	}

	ipRevisionFilterVal, ok := ipRevisionFilterAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_revision_filter expected to be basetypes.StringValue, was: %T`, ipRevisionFilterAttribute))
	}

	maxIpListSizeAttribute, ok := attributes["max_ip_list_size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_ip_list_size is missing from object`)

		return NewMemberGroupValueUnknown(), diags
	}

	maxIpListSizeVal, ok := maxIpListSizeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_ip_list_size expected to be basetypes.Int64Value, was: %T`, maxIpListSizeAttribute))
	}

	pathAttribute, ok := attributes["path"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`path is missing from object`)

		return NewMemberGroupValueUnknown(), diags
	}

	pathVal, ok := pathAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`path expected to be basetypes.StringValue, was: %T`, pathAttribute))
	}

	portAttribute, ok := attributes["port"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`port is missing from object`)

		return NewMemberGroupValueUnknown(), diags
	}

	portVal, ok := portAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`port expected to be basetypes.Int64Value, was: %T`, portAttribute))
	}

	if diags.HasError() {
		return NewMemberGroupValueUnknown(), diags
	}

	return MemberGroupValue{
		IpRevisionFilter: ipRevisionFilterVal,
		MaxIpListSize:    maxIpListSizeVal,
		Path:             pathVal,
		Port:             portVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewMemberGroupValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MemberGroupValue {
	object, diags := NewMemberGroupValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMemberGroupValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MemberGroupType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMemberGroupValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMemberGroupValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMemberGroupValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMemberGroupValueMust(MemberGroupValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MemberGroupType) ValueType(ctx context.Context) attr.Value {
	return MemberGroupValue{}
}

var _ basetypes.ObjectValuable = MemberGroupValue{}

type MemberGroupValue struct {
	IpRevisionFilter basetypes.StringValue `tfsdk:"ip_revision_filter"`
	MaxIpListSize    basetypes.Int64Value  `tfsdk:"max_ip_list_size"`
	Path             basetypes.StringValue `tfsdk:"path"`
	Port             basetypes.Int64Value  `tfsdk:"port"`
	state            attr.ValueState
}

func (v MemberGroupValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["ip_revision_filter"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["max_ip_list_size"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["path"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["port"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.IpRevisionFilter.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_revision_filter"] = val

		val, err = v.MaxIpListSize.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["max_ip_list_size"] = val

		val, err = v.Path.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["path"] = val

		val, err = v.Port.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["port"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MemberGroupValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MemberGroupValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MemberGroupValue) String() string {
	return "MemberGroupValue"
}

func (v MemberGroupValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"ip_revision_filter": basetypes.StringType{},
		"max_ip_list_size":   basetypes.Int64Type{},
		"path":               basetypes.StringType{},
		"port":               basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"ip_revision_filter": v.IpRevisionFilter,
			"max_ip_list_size":   v.MaxIpListSize,
			"path":               v.Path,
			"port":               v.Port,
		})

	return objVal, diags
}

func (v MemberGroupValue) Equal(o attr.Value) bool {
	other, ok := o.(MemberGroupValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.IpRevisionFilter.Equal(other.IpRevisionFilter) {
		return false
	}

	if !v.MaxIpListSize.Equal(other.MaxIpListSize) {
		return false
	}

	if !v.Path.Equal(other.Path) {
		return false
	}

	if !v.Port.Equal(other.Port) {
		return false
	}

	return true
}

func (v MemberGroupValue) Type(ctx context.Context) attr.Type {
	return MemberGroupType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MemberGroupValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"ip_revision_filter": basetypes.StringType{},
		"max_ip_list_size":   basetypes.Int64Type{},
		"path":               basetypes.StringType{},
		"port":               basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = LoadBalancerType{}

type LoadBalancerType struct {
	basetypes.ObjectType
}

func (t LoadBalancerType) Equal(o attr.Type) bool {
	other, ok := o.(LoadBalancerType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t LoadBalancerType) String() string {
	return "LoadBalancerType"
}

func (t LoadBalancerType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewLoadBalancerValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLoadBalancerValueNull(), nil
	}

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	ipAttribute, ok := attributes["ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip is missing from object`)

		return nil, diags
	}

	ipVal, ok := ipAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip expected to be basetypes.StringValue, was: %T`, ipAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.ObjectValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return LoadBalancerValue{
		Id:               idVal,
		Ip:               ipVal,
		Name:             nameVal,
		LoadBalancerType: typeVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewLoadBalancerValueNull() LoadBalancerValue {
	return LoadBalancerValue{
		state: attr.ValueStateNull,
	}
}

func NewLoadBalancerValueUnknown() LoadBalancerValue {
	return LoadBalancerValue{
		state: attr.ValueStateUnknown,
	}
}

func NewLoadBalancerValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (LoadBalancerValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing LoadBalancerValue Attribute Value",
				"While creating a LoadBalancerValue value, a missing attribute value was detected. "+
					"A LoadBalancerValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LoadBalancerValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid LoadBalancerValue Attribute Type",
				"While creating a LoadBalancerValue value, an invalid attribute value was detected. "+
					"A LoadBalancerValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LoadBalancerValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("LoadBalancerValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra LoadBalancerValue Attribute Value",
				"While creating a LoadBalancerValue value, an extra attribute value was detected. "+
					"A LoadBalancerValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra LoadBalancerValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewLoadBalancerValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewLoadBalancerValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	ipAttribute, ok := attributes["ip"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip is missing from object`)

		return NewLoadBalancerValueUnknown(), diags
	}

	ipVal, ok := ipAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip expected to be basetypes.StringValue, was: %T`, ipAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewLoadBalancerValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewLoadBalancerValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.ObjectValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewLoadBalancerValueUnknown(), diags
	}

	return LoadBalancerValue{
		Id:               idVal,
		Ip:               ipVal,
		Name:             nameVal,
		LoadBalancerType: typeVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewLoadBalancerValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) LoadBalancerValue {
	object, diags := NewLoadBalancerValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewLoadBalancerValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t LoadBalancerType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewLoadBalancerValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewLoadBalancerValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLoadBalancerValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewLoadBalancerValueMust(LoadBalancerValue{}.AttributeTypes(ctx), attributes), nil
}

func (t LoadBalancerType) ValueType(ctx context.Context) attr.Value {
	return LoadBalancerValue{}
}

var _ basetypes.ObjectValuable = LoadBalancerValue{}

type LoadBalancerValue struct {
	Id               basetypes.Int64Value  `tfsdk:"id"`
	Ip               basetypes.StringValue `tfsdk:"ip"`
	Name             basetypes.StringValue `tfsdk:"name"`
	LoadBalancerType basetypes.ObjectValue `tfsdk:"type"`
	state            attr.ValueState
}

func (v LoadBalancerValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["ip"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.ObjectType{
		AttrTypes: TypeValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Ip.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.LoadBalancerType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v LoadBalancerValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v LoadBalancerValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v LoadBalancerValue) String() string {
	return "LoadBalancerValue"
}

func (v LoadBalancerValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var loadBalancerTypeVal basetypes.ObjectValue

	if v.LoadBalancerType.IsNull() {
		loadBalancerTypeVal = types.ObjectNull(
			TypeValue{}.AttributeTypes(ctx),
		)
	}

	if v.LoadBalancerType.IsUnknown() {
		loadBalancerTypeVal = types.ObjectUnknown(
			TypeValue{}.AttributeTypes(ctx),
		)
	}

	if !v.LoadBalancerType.IsNull() && !v.LoadBalancerType.IsUnknown() {
		loadBalancerTypeVal = types.ObjectValueMust(
			TypeValue{}.AttributeTypes(ctx),
			v.LoadBalancerType.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.Int64Type{},
		"ip":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.ObjectType{
			AttrTypes: TypeValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"ip":   v.Ip,
			"name": v.Name,
			"type": loadBalancerTypeVal,
		})

	return objVal, diags
}

func (v LoadBalancerValue) Equal(o attr.Value) bool {
	other, ok := o.(LoadBalancerValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Ip.Equal(other.Ip) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.LoadBalancerType.Equal(other.LoadBalancerType) {
		return false
	}

	return true
}

func (v LoadBalancerValue) Type(ctx context.Context) attr.Type {
	return LoadBalancerType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v LoadBalancerValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.Int64Type{},
		"ip":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.ObjectType{
			AttrTypes: TypeValue{}.AttributeTypes(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = TypeType{}

type TypeType struct {
	basetypes.ObjectType
}

func (t TypeType) Equal(o attr.Type) bool {
	other, ok := o.(TypeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TypeType) String() string {
	return "TypeType"
}

func (t TypeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsUnknown() {
		return NewTypeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTypeValueNull(), nil
	}

	attributes := in.Attributes()

	codeAttribute, ok := attributes["code"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`code is missing from object`)

		return nil, diags
	}

	codeVal, ok := codeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`code expected to be basetypes.StringValue, was: %T`, codeAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TypeValue{
		Code:  codeVal,
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTypeValueNull() TypeValue {
	return TypeValue{
		state: attr.ValueStateNull,
	}
}

func NewTypeValueUnknown() TypeValue {
	return TypeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTypeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TypeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TypeValue Attribute Value",
				"While creating a TypeValue value, a missing attribute value was detected. "+
					"A TypeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TypeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TypeValue Attribute Type",
				"While creating a TypeValue value, an invalid attribute value was detected. "+
					"A TypeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TypeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TypeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TypeValue Attribute Value",
				"While creating a TypeValue value, an extra attribute value was detected. "+
					"A TypeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TypeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTypeValueUnknown(), diags
	}

	codeAttribute, ok := attributes["code"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`code is missing from object`)

		return NewTypeValueUnknown(), diags
	}

	codeVal, ok := codeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`code expected to be basetypes.StringValue, was: %T`, codeAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewTypeValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewTypeValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewTypeValueUnknown(), diags
	}

	return TypeValue{
		Code:  codeVal,
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTypeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TypeValue {
	object, diags := NewTypeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTypeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TypeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTypeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTypeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTypeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTypeValueMust(TypeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TypeType) ValueType(ctx context.Context) attr.Value {
	return TypeValue{}
}

var _ basetypes.ObjectValuable = TypeValue{}

type TypeValue struct {
	Code  basetypes.StringValue `tfsdk:"code"`
	Id    basetypes.Int64Value  `tfsdk:"id"`
	Name  basetypes.StringValue `tfsdk:"name"`
	state attr.ValueState
}

func (v TypeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["code"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Code.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["code"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TypeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TypeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TypeValue) String() string {
	return "TypeValue"
}

func (v TypeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"code": basetypes.StringType{},
		"id":   basetypes.Int64Type{},
		"name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"code": v.Code,
			"id":   v.Id,
			"name": v.Name,
		})

	return objVal, diags
}

func (v TypeValue) Equal(o attr.Value) bool {
	other, ok := o.(TypeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Code.Equal(other.Code) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v TypeValue) Type(ctx context.Context) attr.Type {
	return TypeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TypeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"code": basetypes.StringType{},
		"id":   basetypes.Int64Type{},
		"name": basetypes.StringType{},
	}
}
