// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package networkrouternat

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func NetworkRouterNatDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"action": schema.StringAttribute{
				Computed:            true,
				Description:         "The NAT action (e.g. SNAT, DNAT, REFLEXIVE).",
				MarkdownDescription: "The NAT action (e.g. SNAT, DNAT, REFLEXIVE).",
			},
			"date_created": schema.StringAttribute{
				Computed:            true,
				Description:         "The date the NAT rule was created.",
				MarkdownDescription: "The date the NAT rule was created.",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the NAT rule.",
				MarkdownDescription: "The description of the NAT rule.",
			},
			"destination_network": schema.StringAttribute{
				Computed:            true,
				Description:         "Destination network.",
				MarkdownDescription: "Destination network.",
			},
			"destination_ports": schema.StringAttribute{
				Computed:            true,
				Description:         "The destination ports.",
				MarkdownDescription: "The destination ports.",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the NAT rule is enabled.",
				MarkdownDescription: "Whether the NAT rule is enabled.",
			},
			"external_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The external ID of the NAT rule.",
				MarkdownDescription: "The external ID of the NAT rule.",
			},
			"firewall": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The ID of the NAT rule.",
				MarkdownDescription: "The ID of the NAT rule.",
				Validators: []validator.Int64{
					int64validator.ConflictsWith(path.Expressions{path.MatchRoot("name")}...),
				},
			},
			"internal_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The internal ID of the NAT rule.",
				MarkdownDescription: "The internal ID of the NAT rule.",
			},
			"last_updated": schema.StringAttribute{
				Computed:            true,
				Description:         "The date the NAT rule was last updated.",
				MarkdownDescription: "The date the NAT rule was last updated.",
			},
			"match_ipv6destination_prefix": schema.StringAttribute{
				Computed:            true,
				Description:         "The IPv6 destination prefix to match.",
				MarkdownDescription: "The IPv6 destination prefix to match.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the NAT rule.",
				MarkdownDescription: "The name of the NAT rule.",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.Expressions{path.MatchRoot("id")}...),
				},
			},
			"priority": schema.Int64Attribute{
				Computed:            true,
				Description:         "Priority of the NAT rule.",
				MarkdownDescription: "Priority of the NAT rule.",
			},
			"protocol": schema.StringAttribute{
				Computed:            true,
				Description:         "The protocol for the NAT rule.",
				MarkdownDescription: "The protocol for the NAT rule.",
			},
			"provider_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The provider ID of the NAT rule.",
				MarkdownDescription: "The provider ID of the NAT rule.",
			},
			"ref_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The reference ID.",
				MarkdownDescription: "The reference ID.",
			},
			"ref_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The reference type.",
				MarkdownDescription: "The reference type.",
			},
			"router_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the parent network router.",
				MarkdownDescription: "The ID of the parent network router.",
			},
			"service": schema.StringAttribute{
				Computed: true,
			},
			"source_network": schema.StringAttribute{
				Computed:            true,
				Description:         "Source network.",
				MarkdownDescription: "Source network.",
			},
			"source_ports": schema.StringAttribute{
				Computed:            true,
				Description:         "The source ports.",
				MarkdownDescription: "The source ports.",
			},
			"sync_source": schema.StringAttribute{
				Computed:            true,
				Description:         "The synchronization source.",
				MarkdownDescription: "The synchronization source.",
			},
			"translated_ipv4source_prefix": schema.StringAttribute{
				Computed:            true,
				Description:         "The translated IPv4 source prefix.",
				MarkdownDescription: "The translated IPv4 source prefix.",
			},
			"translated_network": schema.StringAttribute{
				Computed:            true,
				Description:         "Translated network.",
				MarkdownDescription: "Translated network.",
			},
			"translated_ports": schema.StringAttribute{
				Computed:            true,
				Description:         "The translated ports.",
				MarkdownDescription: "The translated ports.",
			},
		},
	}
}

type NetworkRouterNatModel struct {
	Action                     types.String `tfsdk:"action"`
	DateCreated                types.String `tfsdk:"date_created"`
	Description                types.String `tfsdk:"description"`
	DestinationNetwork         types.String `tfsdk:"destination_network"`
	DestinationPorts           types.String `tfsdk:"destination_ports"`
	Enabled                    types.Bool   `tfsdk:"enabled"`
	ExternalId                 types.String `tfsdk:"external_id"`
	Firewall                   types.String `tfsdk:"firewall"`
	Id                         types.Int64  `tfsdk:"id"`
	InternalId                 types.String `tfsdk:"internal_id"`
	LastUpdated                types.String `tfsdk:"last_updated"`
	MatchIpv6destinationPrefix types.String `tfsdk:"match_ipv6destination_prefix"`
	Name                       types.String `tfsdk:"name"`
	Priority                   types.Int64  `tfsdk:"priority"`
	Protocol                   types.String `tfsdk:"protocol"`
	ProviderId                 types.String `tfsdk:"provider_id"`
	RefId                      types.String `tfsdk:"ref_id"`
	RefType                    types.String `tfsdk:"ref_type"`
	RouterId                   types.Int64  `tfsdk:"router_id"`
	Service                    types.String `tfsdk:"service"`
	SourceNetwork              types.String `tfsdk:"source_network"`
	SourcePorts                types.String `tfsdk:"source_ports"`
	SyncSource                 types.String `tfsdk:"sync_source"`
	TranslatedIpv4sourcePrefix types.String `tfsdk:"translated_ipv4source_prefix"`
	TranslatedNetwork          types.String `tfsdk:"translated_network"`
	TranslatedPorts            types.String `tfsdk:"translated_ports"`
}
