// Code generated by MockGen. DO NOT EDIT.
// Source: ./client.go

// Package client is a generated GoMock package.
package client

import (
	context "context"
	http "net/http"
	url "net/url"
	reflect "reflect"

	models "github.com/HPE/terraform-provider-hpe/greenlake/cloud/sdk/vmaascmp/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAPIClientHandler is a mock of APIClientHandler interface.
type MockAPIClientHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAPIClientHandlerMockRecorder
}

// MockAPIClientHandlerMockRecorder is the mock recorder for MockAPIClientHandler.
type MockAPIClientHandlerMockRecorder struct {
	mock *MockAPIClientHandler
}

// NewMockAPIClientHandler creates a new mock instance.
func NewMockAPIClientHandler(ctrl *gomock.Controller) *MockAPIClientHandler {
	mock := &MockAPIClientHandler{ctrl: ctrl}
	mock.recorder = &MockAPIClientHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIClientHandler) EXPECT() *MockAPIClientHandlerMockRecorder {
	return m.recorder
}

// ChangeBasePath mocks base method.
func (m *MockAPIClientHandler) ChangeBasePath(path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ChangeBasePath", path)
}

// ChangeBasePath indicates an expected call of ChangeBasePath.
func (mr *MockAPIClientHandlerMockRecorder) ChangeBasePath(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeBasePath", reflect.TypeOf((*MockAPIClientHandler)(nil).ChangeBasePath), path)
}

// GetCMPDetails mocks base method.
func (m *MockAPIClientHandler) GetCMPDetails(ctx context.Context) (models.TFMorpheusDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCMPDetails", ctx)
	ret0, _ := ret[0].(models.TFMorpheusDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCMPDetails indicates an expected call of GetCMPDetails.
func (mr *MockAPIClientHandlerMockRecorder) GetCMPDetails(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCMPDetails", reflect.TypeOf((*MockAPIClientHandler)(nil).GetCMPDetails), ctx)
}

// GetSCMVersion mocks base method.
func (m *MockAPIClientHandler) GetSCMVersion() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSCMVersion")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetSCMVersion indicates an expected call of GetSCMVersion.
func (mr *MockAPIClientHandlerMockRecorder) GetSCMVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSCMVersion", reflect.TypeOf((*MockAPIClientHandler)(nil).GetSCMVersion))
}

// SetCMPVersion mocks base method.
func (m *MockAPIClientHandler) SetCMPVersion(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCMPVersion", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCMPVersion indicates an expected call of SetCMPVersion.
func (mr *MockAPIClientHandlerMockRecorder) SetCMPVersion(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCMPVersion", reflect.TypeOf((*MockAPIClientHandler)(nil).SetCMPVersion), ctx)
}

// SetHost mocks base method.
func (m *MockAPIClientHandler) SetHost(host string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHost", host)
}

// SetHost indicates an expected call of SetHost.
func (mr *MockAPIClientHandlerMockRecorder) SetHost(host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHost", reflect.TypeOf((*MockAPIClientHandler)(nil).SetHost), host)
}

// SetMeta mocks base method.
func (m *MockAPIClientHandler) SetMeta(meta interface{}, fn SetScmClientToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMeta", meta, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMeta indicates an expected call of SetMeta.
func (mr *MockAPIClientHandlerMockRecorder) SetMeta(meta, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMeta", reflect.TypeOf((*MockAPIClientHandler)(nil).SetMeta), meta, fn)
}

// SetMetaFnAndVersion mocks base method.
func (m *MockAPIClientHandler) SetMetaFnAndVersion(meta interface{}, version int, fn SetScmClientToken) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMetaFnAndVersion", meta, version, fn)
}

// SetMetaFnAndVersion indicates an expected call of SetMetaFnAndVersion.
func (mr *MockAPIClientHandlerMockRecorder) SetMetaFnAndVersion(meta, version, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetaFnAndVersion", reflect.TypeOf((*MockAPIClientHandler)(nil).SetMetaFnAndVersion), meta, version, fn)
}

// callAPI mocks base method.
func (m *MockAPIClientHandler) callAPI(request *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "callAPI", request)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// callAPI indicates an expected call of callAPI.
func (mr *MockAPIClientHandlerMockRecorder) callAPI(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "callAPI", reflect.TypeOf((*MockAPIClientHandler)(nil).callAPI), request)
}

// decode mocks base method.
func (m *MockAPIClientHandler) decode(v interface{}, b []byte, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "decode", v, b, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// decode indicates an expected call of decode.
func (mr *MockAPIClientHandlerMockRecorder) decode(v, b, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "decode", reflect.TypeOf((*MockAPIClientHandler)(nil).decode), v, b, contentType)
}

// getHost mocks base method.
func (m *MockAPIClientHandler) getHost() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getHost")
	ret0, _ := ret[0].(string)
	return ret0
}

// getHost indicates an expected call of getHost.
func (mr *MockAPIClientHandlerMockRecorder) getHost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getHost", reflect.TypeOf((*MockAPIClientHandler)(nil).getHost))
}

// getVersion mocks base method.
func (m *MockAPIClientHandler) getVersion() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getVersion")
	ret0, _ := ret[0].(int)
	return ret0
}

// getVersion indicates an expected call of getVersion.
func (mr *MockAPIClientHandlerMockRecorder) getVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getVersion", reflect.TypeOf((*MockAPIClientHandler)(nil).getVersion))
}

// prepareRequest mocks base method.
func (m *MockAPIClientHandler) prepareRequest(ctx context.Context, path, method string, postBody interface{}, headerParams map[string]string, queryParams, formParams url.Values, fileName string, fileBytes []byte) (*http.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "prepareRequest", ctx, path, method, postBody, headerParams, queryParams, formParams, fileName, fileBytes)
	ret0, _ := ret[0].(*http.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// prepareRequest indicates an expected call of prepareRequest.
func (mr *MockAPIClientHandlerMockRecorder) prepareRequest(ctx, path, method, postBody, headerParams, queryParams, formParams, fileName, fileBytes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "prepareRequest", reflect.TypeOf((*MockAPIClientHandler)(nil).prepareRequest), ctx, path, method, postBody, headerParams, queryParams, formParams, fileName, fileBytes)
}
