// (C) Copyright 2025 Hewlett Packard Enterprise Development LP

package task

//go:generate go run ../../../../../cmd/render -out examples/resources/morpheus_task_chef_bootstrap/resource.tf task_chef_bootstrap_resource.tf.tmpl Name terraform_example_chef Code terraform_example_chef Labels "[\"demo\", \"terraform\"]" ChefServerId 9 Environment dev RunList "role[web]" DataBagKey test123 DataBagKeyPath /etc/chef/databag_secret NodeName demonode NodeAttributes "{\n  \"test\":\"demo\"\n}" Retryable true RetryCount 1 RetryDelaySeconds 10 AllowCustomConfig true Visibility public
//go:generate go run ../../../../../cmd/render -out examples/resources/morpheus_task_email/resource.tf task_email_resource.tf.tmpl Name tfexample_email Code tfexample_email Labels "[\"demo\", \"terraform\"]" EmailAddress "<%=instance.createdByEmail%>" Subject "<%=instance.hostname%> provisioning complete" Source local Content "Your instance <%=instance.hostname%> was provisioned." SkipWrappedEmailTemplate false Retryable true RetryCount 1 RetryDelaySeconds 10 AllowCustomConfig true
//go:generate go run ../../../../../cmd/render -out examples/resources/morpheus_task_email/resource_git.tf task_email_resource_git.tf.tmpl Name tfexample_email_git Code tfexample_email_git Labels "[\"demo\", \"terraform\"]" EmailAddress "<%=instance.createdByEmail%>" Subject "<%=instance.hostname%> provisioning complete" Source repository ContentPath example.txt RepositoryId 1 VersionRef main SkipWrappedEmailTemplate false Retryable true RetryCount 1 RetryDelaySeconds 10 AllowCustomConfig true
//go:generate go run ../../../../../cmd/render -out examples/resources/morpheus_task_email/resource_url.tf task_email_resource_url.tf.tmpl Name tfexample_email_url Code tfexample_email_url Labels "[\"demo\", \"terraform\"]" EmailAddress "<%=instance.createdByEmail%>" Subject "<%=instance.hostname%> provisioning complete" Source url ContentUrl "https://example.com/example.txt" SkipWrappedEmailTemplate false Retryable true RetryCount 1 RetryDelaySeconds 10 AllowCustomConfig true
//go:generate go run ../../../../../cmd/render -out examples/resources/morpheus_task_groovy_script/resource.tf task_groovy_script_resource.tf.tmpl Name tfexample_groovy_local Code tfexample_groovy_local Labels "[\"demo\", \"terraform\"]" SourceType local ScriptContent "println \"hello\"" Retryable true RetryCount 1 RetryDelaySeconds 10 AllowCustomConfig true
//go:generate go run ../../../../../cmd/render -out examples/resources/morpheus_task_groovy_script/resource_git.tf task_groovy_script_resource_git.tf.tmpl Name tfexample_groovy_git Code tfexample_groovy_git Labels "[\"demo\", \"terraform\"]" SourceType repository ResultType json ScriptPath example.groovy VersionRef master RepositoryId 1 Retryable true RetryCount 1 RetryDelaySeconds 10 AllowCustomConfig true
//go:generate go run ../../../../../cmd/render -out examples/resources/morpheus_task_groovy_script/resource_url.tf task_groovy_script_resource_url.tf.tmpl Name tfexample_groovy_url Code tfexample_groovy_url Labels "[\"demo\", \"terraform\"]" SourceType url ResultType json ScriptPath "https://example.com/example.groovy" Retryable true RetryCount 1 RetryDelaySeconds 10 AllowCustomConfig true
//go:generate go run ../../../../../cmd/render -out examples/resources/morpheus_task_javascript/resource.tf task_javascript_resource.tf.tmpl Name tfexample_javascript Code tfexample_javascript Labels "[\"demo\", \"terraform\"]" ScriptContent "console.log(\"testing\")" Retryable true RetryCount 1 RetryDelaySeconds 10 AllowCustomConfig true
