// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package backupinstance

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func BackupInstanceDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"container_id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the container (workload) being backed up",
				MarkdownDescription: "The ID of the container (workload) being backed up",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the backup is enabled",
				MarkdownDescription: "Whether the backup is enabled",
			},
			"id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "ID of the Instance Backup",
				MarkdownDescription: "ID of the Instance Backup",
				Validators: []validator.Int64{
					int64validator.ConflictsWith(path.Expressions{path.MatchRoot("name")}...),
				},
			},
			"instance_id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the instance being backed up",
				MarkdownDescription: "The ID of the instance being backed up",
			},
			"job_id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the Backup Job associated with this backup",
				MarkdownDescription: "The ID of the Backup Job associated with this backup",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Name of the Instance Backup",
				MarkdownDescription: "Name of the Instance Backup",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.Expressions{path.MatchRoot("id")}...),
				},
			},
			"storage_provider_id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the storage provider (Bucket or File Share) used for this backup",
				MarkdownDescription: "The ID of the storage provider (Bucket or File Share) used for this backup",
			},
		},
	}
}

type BackupInstanceModel struct {
	ContainerId       types.Int64  `tfsdk:"container_id"`
	Enabled           types.Bool   `tfsdk:"enabled"`
	Id                types.Int64  `tfsdk:"id"`
	InstanceId        types.Int64  `tfsdk:"instance_id"`
	JobId             types.Int64  `tfsdk:"job_id"`
	Name              types.String `tfsdk:"name"`
	StorageProviderId types.Int64  `tfsdk:"storage_provider_id"`
}
