// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package option_list

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OptionListResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_type": schema.StringAttribute{
				Optional:            true,
				Description:         "The API type of the option list.",
				MarkdownDescription: "The API type of the option list.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Description:         "The description of the option type list.",
				MarkdownDescription: "The description of the option type list.",
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the option type list.",
				MarkdownDescription: "The ID of the option type list.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the option type list.",
				MarkdownDescription: "The name of the option type list.",
			},
			"real_time": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether the option list is fetched in real time.",
				MarkdownDescription: "Whether the option list is fetched in real time.",
				Default:             booldefault.StaticBool(false),
			},
			"source_url": schema.StringAttribute{
				Optional:            true,
				Description:         "The source URL for the option list.",
				MarkdownDescription: "The source URL for the option list.",
			},
			"type": schema.StringAttribute{
				Optional:            true,
				Description:         "The type of the option list (rest, manual, ldap, api).",
				MarkdownDescription: "The type of the option list (rest, manual, ldap, api).",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"rest",
						"api",
						"ldap",
						"manual",
					),
				},
			},
			"visibility": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The visibility of the option type list.",
				MarkdownDescription: "The visibility of the option type list.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"private",
						"public",
					),
				},
				Default: stringdefault.StaticString("private"),
			},
		},
		Description:         "Manages a Morpheus Library Option Type List resource.",
		MarkdownDescription: "Manages a Morpheus Library Option Type List resource.",
	}
}

type OptionListModel struct {
	ApiType     types.String `tfsdk:"api_type"`
	Description types.String `tfsdk:"description"`
	Id          types.Int64  `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	RealTime    types.Bool   `tfsdk:"real_time"`
	SourceUrl   types.String `tfsdk:"source_url"`
	Type        types.String `tfsdk:"type"`
	Visibility  types.String `tfsdk:"visibility"`
}
