network_group:
  description: "Manages a Morpheus Network Group resource."
  templates:
    tenantIds:
      set:
        computed_optional_required: optional
        description: List of tenant account IDs that are allowed access.
        element_type:
          int64: {}
    resourcePermissions:
      single_nested:
        computed_optional_required: optional
        description: Resource permissions for group and service plan access.
        attributes:
        - name: all
          bool:
            computed_optional_required: optional
            description: Pass true to allow access to all groups.
        - name: group_ids
          list:
            computed_optional_required: optional
            description: List of group IDs allowed access.
            element_type:
              int64: {}
        - name: all_plans
          bool:
            computed_optional_required: optional
            description: Pass true to allow access to all service plans.
        - name: plan_ids
          list:
            computed_optional_required: optional
            description: List of service plan IDs allowed access.
            element_type:
              int64: {}
  moves:
    - network_group: ""
    - template-tenantIds: tenant_ids
    - template-resourcePermissions: resource_permissions
  removes:
    - networks
    - subnets
    - success
    - tenants
    - tenant_permissions
    - resource_permission
  overrides:
    active:
      computed_optional_required: computed_optional
      description: Whether the network group is active.
      default: true
      state_for_unknown: true
    description:
      computed_optional_required: optional
      description: The description of the network group.
    id:
      computed_optional_required: computed
      description: The ID of the network group.
      state_for_unknown: true
    name:
      computed_optional_required: required
      description: The name of the network group.
    visibility:
      computed_optional_required: computed_optional
      description: The visibility of the network group (public or private).
      default: "private"
      one_of: [public, private]
      state_for_unknown: true
