cluster_namespace:
  moves:
    - namespace: ""                      # unnest wrapper (components/schemas/clusterNamespace.yaml)
  removes:
    - external_id                        # (components/schemas/clusterNamespace.yaml) internal
    - permissions                        # (components/schemas/clusterNamespace.yaml) complex object
    - status                             # (components/schemas/clusterNamespace.yaml) read-only
  overrides:
    id:
      computed_optional_required: computed_optional
      description: The ID of the cluster namespace.
      conflicts_with: ["name"]
    name:
      computed_optional_required: computed_optional
      description: The name of the cluster namespace.
      conflicts_with: ["id"]
    cluster_id:
      computed_optional_required: required
      description: The ID of the parent cluster.
