// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package monitoringgroup

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func MonitoringGroupDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the monitoring group.",
				MarkdownDescription: "The description of the monitoring group.",
			},
			"id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The ID of the monitoring group.",
				MarkdownDescription: "The ID of the monitoring group.",
				Validators: []validator.Int64{
					int64validator.ConflictsWith(path.Expressions{path.MatchRoot("name")}...),
				},
			},
			"in_uptime": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the group affects account-wide availability calculations.",
				MarkdownDescription: "Whether the group affects account-wide availability calculations.",
			},
			"min_happy": schema.Int64Attribute{
				Computed:            true,
				Description:         "Minimum number of checks that must be happy to keep the group healthy.",
				MarkdownDescription: "Minimum number of checks that must be happy to keep the group healthy.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the monitoring group.",
				MarkdownDescription: "The name of the monitoring group.",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.Expressions{path.MatchRoot("id")}...),
				},
			},
			"severity": schema.StringAttribute{
				Computed:            true,
				Description:         "Maximum severity level this group can incur on an incident when failing.",
				MarkdownDescription: "Maximum severity level this group can incur on an incident when failing.",
			},
		},
	}
}

type MonitoringGroupModel struct {
	Description types.String `tfsdk:"description"`
	Id          types.Int64  `tfsdk:"id"`
	InUptime    types.Bool   `tfsdk:"in_uptime"`
	MinHappy    types.Int64  `tfsdk:"min_happy"`
	Name        types.String `tfsdk:"name"`
	Severity    types.String `tfsdk:"severity"`
}
