/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ListTenantAvailableRoles200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTenantAvailableRoles200Response{}

// ListTenantAvailableRoles200Response struct for ListTenantAvailableRoles200Response
type ListTenantAvailableRoles200Response struct {
	Roles                []ListTenantAvailableRoles200ResponseRolesInner `json:"roles,omitempty"`
	AdditionalProperties map[string]interface{}                          `json:",remain"`
}

type _ListTenantAvailableRoles200Response ListTenantAvailableRoles200Response

func (o ListTenantAvailableRoles200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTenantAvailableRoles200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableListTenantAvailableRoles200Response struct {
	value *ListTenantAvailableRoles200Response
	isSet bool
}

func (v NullableListTenantAvailableRoles200Response) Get() *ListTenantAvailableRoles200Response {
	return v.value
}

func (v *NullableListTenantAvailableRoles200Response) Set(val *ListTenantAvailableRoles200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListTenantAvailableRoles200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListTenantAvailableRoles200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTenantAvailableRoles200Response(val *ListTenantAvailableRoles200Response) *NullableListTenantAvailableRoles200Response {
	return &NullableListTenantAvailableRoles200Response{value: val, isSet: true}
}

func (v NullableListTenantAvailableRoles200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTenantAvailableRoles200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableListTenantAvailableRoles200Response) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *ListTenantAvailableRoles200Response) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
