/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the StorageDatastoreConfigAlletraMPBmaas type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageDatastoreConfigAlletraMPBmaas{}

// StorageDatastoreConfigAlletraMPBmaas HPE Alletra Storage MP Bare Metal (BMaaS) datastore configuration
type StorageDatastoreConfigAlletraMPBmaas struct {
	// Storage protocol to use, can be 'iSCSI' or 'FC'
	ProtocolType         string                 `json:"protocolType"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _StorageDatastoreConfigAlletraMPBmaas StorageDatastoreConfigAlletraMPBmaas

func (o StorageDatastoreConfigAlletraMPBmaas) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageDatastoreConfigAlletraMPBmaas) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["protocolType"] = o.ProtocolType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableStorageDatastoreConfigAlletraMPBmaas struct {
	value *StorageDatastoreConfigAlletraMPBmaas
	isSet bool
}

func (v NullableStorageDatastoreConfigAlletraMPBmaas) Get() *StorageDatastoreConfigAlletraMPBmaas {
	return v.value
}

func (v *NullableStorageDatastoreConfigAlletraMPBmaas) Set(val *StorageDatastoreConfigAlletraMPBmaas) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageDatastoreConfigAlletraMPBmaas) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageDatastoreConfigAlletraMPBmaas) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageDatastoreConfigAlletraMPBmaas(val *StorageDatastoreConfigAlletraMPBmaas) *NullableStorageDatastoreConfigAlletraMPBmaas {
	return &NullableStorageDatastoreConfigAlletraMPBmaas{value: val, isSet: true}
}

func (v NullableStorageDatastoreConfigAlletraMPBmaas) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageDatastoreConfigAlletraMPBmaas) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableStorageDatastoreConfigAlletraMPBmaas) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *StorageDatastoreConfigAlletraMPBmaas) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
