/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// very silly way of avoiding `"fmt" imported and not used` errors
var _ fmt.Stringer

// UpdateCatalogItemTypeRequestCatalogItemType struct for UpdateCatalogItemTypeRequestCatalogItemType
type UpdateCatalogItemTypeRequestCatalogItemType struct {
	UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf  *UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf
	UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1 *UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1
	UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2 *UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2
}

func (dst *UpdateCatalogItemTypeRequestCatalogItemType) UnmarshalMapstructure(data any) (any, error) {
	if dst == nil {
		dst = &UpdateCatalogItemTypeRequestCatalogItemType{}
	}

	mapstructDecode(data, &dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf)

	if IsEmpty(dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf) {
		dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf = nil
	}

	mapstructDecode(data, &dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1)

	if IsEmpty(dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1) {
		dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1 = nil
	}

	mapstructDecode(data, &dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2)

	if IsEmpty(dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2) {
		dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2 = nil
	}

	return dst, nil
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *UpdateCatalogItemTypeRequestCatalogItemType) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf
	err = json.Unmarshal(data, &dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf)
	if err == nil {
		jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf, merrUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf := json.Marshal(dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf)
		var zeroUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf
		jsonZeroUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf, _ := json.Marshal(&zeroUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf != nil || string(jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf) == "{}" || (len(jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf) > 0 && jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf[0] == '{' && string(jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf) == string(jsonZeroUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf)) {
			dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf = nil
		} else {
			return nil // data stored in dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf, return on the first match
		}
	} else {
		dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf = nil
	}

	// try to unmarshal JSON data into UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1
	err = json.Unmarshal(data, &dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1)
	if err == nil {
		jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1, merrUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1 := json.Marshal(dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1)
		var zeroUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1 UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1
		jsonZeroUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1, _ := json.Marshal(&zeroUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1 != nil || string(jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1) == "{}" || (len(jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1) > 0 && jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1[0] == '{' && string(jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1) == string(jsonZeroUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1)) {
			dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1 = nil
		} else {
			return nil // data stored in dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1, return on the first match
		}
	} else {
		dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1 = nil
	}

	// try to unmarshal JSON data into UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2
	err = json.Unmarshal(data, &dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2)
	if err == nil {
		jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2, merrUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2 := json.Marshal(dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2)
		var zeroUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2 UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2
		jsonZeroUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2, _ := json.Marshal(&zeroUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2 != nil || string(jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2) == "{}" || (len(jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2) > 0 && jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2[0] == '{' && string(jsonUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2) == string(jsonZeroUpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2)) {
			dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2 = nil
		} else {
			return nil // data stored in dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2, return on the first match
		}
	} else {
		dst.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2 = nil
	}

	// An empty object (or empty payload) legitimately matches no variant;
	// treat it as "no data" rather than a hard validation error so that an
	// empty value round-trips cleanly instead of failing to unmarshal.
	if string(data) == "{}" || string(data) == "" {
		return nil
	}
	return NewResponseValidationError("data failed to match schemas in anyOf(UpdateCatalogItemTypeRequestCatalogItemType)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UpdateCatalogItemTypeRequestCatalogItemType) MarshalJSON() ([]byte, error) {
	if src.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf != nil {
		return json.Marshal(&src.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf)
	}

	if src.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1 != nil {
		return json.Marshal(&src.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf1)
	}

	if src.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2 != nil {
		return json.Marshal(&src.UpdateCatalogItemTypeRequestCatalogItemTypeAnyOf2)
	}

	return []byte("{}"), nil // no variant set: marshal an empty object rather than returning (nil,nil), which encoding/json rejects as "unexpected end of JSON input"
}

type NullableUpdateCatalogItemTypeRequestCatalogItemType struct {
	value *UpdateCatalogItemTypeRequestCatalogItemType
	isSet bool
}

func (v NullableUpdateCatalogItemTypeRequestCatalogItemType) Get() *UpdateCatalogItemTypeRequestCatalogItemType {
	return v.value
}

func (v *NullableUpdateCatalogItemTypeRequestCatalogItemType) Set(val *UpdateCatalogItemTypeRequestCatalogItemType) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCatalogItemTypeRequestCatalogItemType) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCatalogItemTypeRequestCatalogItemType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCatalogItemTypeRequestCatalogItemType(val *UpdateCatalogItemTypeRequestCatalogItemType) *NullableUpdateCatalogItemTypeRequestCatalogItemType {
	return &NullableUpdateCatalogItemTypeRequestCatalogItemType{value: val, isSet: true}
}

func (v NullableUpdateCatalogItemTypeRequestCatalogItemType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCatalogItemTypeRequestCatalogItemType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUpdateCatalogItemTypeRequestCatalogItemType) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}
