/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// very silly way of avoiding `"fmt" imported and not used` errors
var _ fmt.Stringer

// UpdateVDIPools200Response struct for UpdateVDIPools200Response
type UpdateVDIPools200Response struct {
	UpdateVDIPools200ResponseAnyOf  *UpdateVDIPools200ResponseAnyOf
	UpdateVDIPools200ResponseAnyOf1 *UpdateVDIPools200ResponseAnyOf1
}

func (dst *UpdateVDIPools200Response) UnmarshalMapstructure(data any) (any, error) {
	if dst == nil {
		dst = &UpdateVDIPools200Response{}
	}

	mapstructDecode(data, &dst.UpdateVDIPools200ResponseAnyOf)

	if IsEmpty(dst.UpdateVDIPools200ResponseAnyOf) {
		dst.UpdateVDIPools200ResponseAnyOf = nil
	}

	mapstructDecode(data, &dst.UpdateVDIPools200ResponseAnyOf1)

	if IsEmpty(dst.UpdateVDIPools200ResponseAnyOf1) {
		dst.UpdateVDIPools200ResponseAnyOf1 = nil
	}

	return dst, nil
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *UpdateVDIPools200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into UpdateVDIPools200ResponseAnyOf
	err = json.Unmarshal(data, &dst.UpdateVDIPools200ResponseAnyOf)
	if err == nil {
		jsonUpdateVDIPools200ResponseAnyOf, merrUpdateVDIPools200ResponseAnyOf := json.Marshal(dst.UpdateVDIPools200ResponseAnyOf)
		var zeroUpdateVDIPools200ResponseAnyOf UpdateVDIPools200ResponseAnyOf
		jsonZeroUpdateVDIPools200ResponseAnyOf, _ := json.Marshal(&zeroUpdateVDIPools200ResponseAnyOf)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrUpdateVDIPools200ResponseAnyOf != nil || string(jsonUpdateVDIPools200ResponseAnyOf) == "{}" || (len(jsonUpdateVDIPools200ResponseAnyOf) > 0 && jsonUpdateVDIPools200ResponseAnyOf[0] == '{' && string(jsonUpdateVDIPools200ResponseAnyOf) == string(jsonZeroUpdateVDIPools200ResponseAnyOf)) {
			dst.UpdateVDIPools200ResponseAnyOf = nil
		} else {
			return nil // data stored in dst.UpdateVDIPools200ResponseAnyOf, return on the first match
		}
	} else {
		dst.UpdateVDIPools200ResponseAnyOf = nil
	}

	// try to unmarshal JSON data into UpdateVDIPools200ResponseAnyOf1
	err = json.Unmarshal(data, &dst.UpdateVDIPools200ResponseAnyOf1)
	if err == nil {
		jsonUpdateVDIPools200ResponseAnyOf1, merrUpdateVDIPools200ResponseAnyOf1 := json.Marshal(dst.UpdateVDIPools200ResponseAnyOf1)
		var zeroUpdateVDIPools200ResponseAnyOf1 UpdateVDIPools200ResponseAnyOf1
		jsonZeroUpdateVDIPools200ResponseAnyOf1, _ := json.Marshal(&zeroUpdateVDIPools200ResponseAnyOf1)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrUpdateVDIPools200ResponseAnyOf1 != nil || string(jsonUpdateVDIPools200ResponseAnyOf1) == "{}" || (len(jsonUpdateVDIPools200ResponseAnyOf1) > 0 && jsonUpdateVDIPools200ResponseAnyOf1[0] == '{' && string(jsonUpdateVDIPools200ResponseAnyOf1) == string(jsonZeroUpdateVDIPools200ResponseAnyOf1)) {
			dst.UpdateVDIPools200ResponseAnyOf1 = nil
		} else {
			return nil // data stored in dst.UpdateVDIPools200ResponseAnyOf1, return on the first match
		}
	} else {
		dst.UpdateVDIPools200ResponseAnyOf1 = nil
	}

	// An empty object (or empty payload) legitimately matches no variant;
	// treat it as "no data" rather than a hard validation error so that an
	// empty value round-trips cleanly instead of failing to unmarshal.
	if string(data) == "{}" || string(data) == "" {
		return nil
	}
	return NewResponseValidationError("data failed to match schemas in anyOf(UpdateVDIPools200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UpdateVDIPools200Response) MarshalJSON() ([]byte, error) {
	if src.UpdateVDIPools200ResponseAnyOf != nil {
		return json.Marshal(&src.UpdateVDIPools200ResponseAnyOf)
	}

	if src.UpdateVDIPools200ResponseAnyOf1 != nil {
		return json.Marshal(&src.UpdateVDIPools200ResponseAnyOf1)
	}

	return []byte("{}"), nil // no variant set: marshal an empty object rather than returning (nil,nil), which encoding/json rejects as "unexpected end of JSON input"
}

type NullableUpdateVDIPools200Response struct {
	value *UpdateVDIPools200Response
	isSet bool
}

func (v NullableUpdateVDIPools200Response) Get() *UpdateVDIPools200Response {
	return v.value
}

func (v *NullableUpdateVDIPools200Response) Set(val *UpdateVDIPools200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateVDIPools200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateVDIPools200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateVDIPools200Response(val *UpdateVDIPools200Response) *NullableUpdateVDIPools200Response {
	return &NullableUpdateVDIPools200Response{value: val, isSet: true}
}

func (v NullableUpdateVDIPools200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateVDIPools200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUpdateVDIPools200Response) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}
