/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// very silly way of avoiding `"fmt" imported and not used` errors
var _ fmt.Stringer

// GenerateSupportBundleRequestContentsInner struct for GenerateSupportBundleRequestContentsInner
type GenerateSupportBundleRequestContentsInner struct {
	Any *interface{}
}

func (dst *GenerateSupportBundleRequestContentsInner) UnmarshalMapstructure(data any) (any, error) {
	if dst == nil {
		dst = &GenerateSupportBundleRequestContentsInner{}
	}

	mapstructDecode(data, &dst.Any)

	if IsEmpty(dst.Any) {
		dst.Any = nil
	}

	return dst, nil
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GenerateSupportBundleRequestContentsInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Any
	err = json.Unmarshal(data, &dst.Any)
	if err == nil {
		jsonAny, merrAny := json.Marshal(dst.Any)
		var zeroAny interface{}
		jsonZeroAny, _ := json.Marshal(&zeroAny)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrAny != nil || string(jsonAny) == "{}" || (len(jsonAny) > 0 && jsonAny[0] == '{' && string(jsonAny) == string(jsonZeroAny)) {
			dst.Any = nil
		} else {
			return nil // data stored in dst.Any, return on the first match
		}
	} else {
		dst.Any = nil
	}

	// An empty object (or empty payload) legitimately matches no variant;
	// treat it as "no data" rather than a hard validation error so that an
	// empty value round-trips cleanly instead of failing to unmarshal.
	if string(data) == "{}" || string(data) == "" {
		return nil
	}
	return NewResponseValidationError("data failed to match schemas in anyOf(GenerateSupportBundleRequestContentsInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GenerateSupportBundleRequestContentsInner) MarshalJSON() ([]byte, error) {
	if src.Any != nil {
		return json.Marshal(&src.Any)
	}

	return []byte("{}"), nil // no variant set: marshal an empty object rather than returning (nil,nil), which encoding/json rejects as "unexpected end of JSON input"
}

type NullableGenerateSupportBundleRequestContentsInner struct {
	value *GenerateSupportBundleRequestContentsInner
	isSet bool
}

func (v NullableGenerateSupportBundleRequestContentsInner) Get() *GenerateSupportBundleRequestContentsInner {
	return v.value
}

func (v *NullableGenerateSupportBundleRequestContentsInner) Set(val *GenerateSupportBundleRequestContentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateSupportBundleRequestContentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateSupportBundleRequestContentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateSupportBundleRequestContentsInner(val *GenerateSupportBundleRequestContentsInner) *NullableGenerateSupportBundleRequestContentsInner {
	return &NullableGenerateSupportBundleRequestContentsInner{value: val, isSet: true}
}

func (v NullableGenerateSupportBundleRequestContentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateSupportBundleRequestContentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGenerateSupportBundleRequestContentsInner) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}
