/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup{}

// UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup struct for UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup
type UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup struct {
	Id                   *int64                 `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup

func (o UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup struct {
	value *UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup
	isSet bool
}

func (v NullableUpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup) Get() *UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup {
	return v.value
}

func (v *NullableUpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup) Set(val *UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup(val *UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup) *NullableUpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup {
	return &NullableUpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup{value: val, isSet: true}
}

func (v NullableUpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *UpdateInstanceNetworkInterface200ResponseAllOfOneOfNetworkInterfaceNetworkGroup) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
