/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// very silly way of avoiding `"fmt" imported and not used` errors
var _ fmt.Stringer

// LoadBalancerInstanceUpdateConfig struct for LoadBalancerInstanceUpdateConfig
type LoadBalancerInstanceUpdateConfig struct {
	NSXVirtualServerConfigObject2 *NSXVirtualServerConfigObject2
	MapmapOfStringAny             *map[string]interface{}
}

func (dst *LoadBalancerInstanceUpdateConfig) UnmarshalMapstructure(data any) (any, error) {
	if dst == nil {
		dst = &LoadBalancerInstanceUpdateConfig{}
	}

	mapstructDecode(data, &dst.NSXVirtualServerConfigObject2)

	if IsEmpty(dst.NSXVirtualServerConfigObject2) {
		dst.NSXVirtualServerConfigObject2 = nil
	}

	mapstructDecode(data, &dst.MapmapOfStringAny)

	if IsEmpty(dst.MapmapOfStringAny) {
		dst.MapmapOfStringAny = nil
	}

	return dst, nil
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *LoadBalancerInstanceUpdateConfig) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into NSXVirtualServerConfigObject2
	err = json.Unmarshal(data, &dst.NSXVirtualServerConfigObject2)
	if err == nil {
		jsonNSXVirtualServerConfigObject2, merrNSXVirtualServerConfigObject2 := json.Marshal(dst.NSXVirtualServerConfigObject2)
		var zeroNSXVirtualServerConfigObject2 NSXVirtualServerConfigObject2
		jsonZeroNSXVirtualServerConfigObject2, _ := json.Marshal(&zeroNSXVirtualServerConfigObject2)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrNSXVirtualServerConfigObject2 != nil || string(jsonNSXVirtualServerConfigObject2) == "{}" || (len(jsonNSXVirtualServerConfigObject2) > 0 && jsonNSXVirtualServerConfigObject2[0] == '{' && string(jsonNSXVirtualServerConfigObject2) == string(jsonZeroNSXVirtualServerConfigObject2)) {
			dst.NSXVirtualServerConfigObject2 = nil
		} else {
			return nil // data stored in dst.NSXVirtualServerConfigObject2, return on the first match
		}
	} else {
		dst.NSXVirtualServerConfigObject2 = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, merrMapmapOfStringAny := json.Marshal(dst.MapmapOfStringAny)
		var zeroMapmapOfStringAny map[string]interface{}
		jsonZeroMapmapOfStringAny, _ := json.Marshal(&zeroMapmapOfStringAny)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrMapmapOfStringAny != nil || string(jsonMapmapOfStringAny) == "{}" || (len(jsonMapmapOfStringAny) > 0 && jsonMapmapOfStringAny[0] == '{' && string(jsonMapmapOfStringAny) == string(jsonZeroMapmapOfStringAny)) {
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	// An empty object (or empty payload) legitimately matches no variant;
	// treat it as "no data" rather than a hard validation error so that an
	// empty value round-trips cleanly instead of failing to unmarshal.
	if string(data) == "{}" || string(data) == "" {
		return nil
	}
	return NewResponseValidationError("data failed to match schemas in anyOf(LoadBalancerInstanceUpdateConfig)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src LoadBalancerInstanceUpdateConfig) MarshalJSON() ([]byte, error) {
	if src.NSXVirtualServerConfigObject2 != nil {
		return json.Marshal(&src.NSXVirtualServerConfigObject2)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return []byte("{}"), nil // no variant set: marshal an empty object rather than returning (nil,nil), which encoding/json rejects as "unexpected end of JSON input"
}

type NullableLoadBalancerInstanceUpdateConfig struct {
	value *LoadBalancerInstanceUpdateConfig
	isSet bool
}

func (v NullableLoadBalancerInstanceUpdateConfig) Get() *LoadBalancerInstanceUpdateConfig {
	return v.value
}

func (v *NullableLoadBalancerInstanceUpdateConfig) Set(val *LoadBalancerInstanceUpdateConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableLoadBalancerInstanceUpdateConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableLoadBalancerInstanceUpdateConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoadBalancerInstanceUpdateConfig(val *LoadBalancerInstanceUpdateConfig) *NullableLoadBalancerInstanceUpdateConfig {
	return &NullableLoadBalancerInstanceUpdateConfig{value: val, isSet: true}
}

func (v NullableLoadBalancerInstanceUpdateConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoadBalancerInstanceUpdateConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableLoadBalancerInstanceUpdateConfig) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}
