/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet{}

// GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet struct for GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet
type GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet struct {
	Id                   *int64                 `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet

func (o GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet struct {
	value *GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet
	isSet bool
}

func (v NullableGetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet) Get() *GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet {
	return v.value
}

func (v *NullableGetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet) Set(val *GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet(val *GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet) *NullableGetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet {
	return &NullableGetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet{value: val, isSet: true}
}

func (v NullableGetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GetGuidances200ResponseDiscoveryAnyOfResourceInterfacesInnerSubnet) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
