/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// very silly way of avoiding `"fmt" imported and not used` errors
var _ fmt.Stringer

// GetAlerts200ResponseAllOfChecksInnerConfig struct for GetAlerts200ResponseAllOfChecksInnerConfig
type GetAlerts200ResponseAllOfChecksInnerConfig struct {
	ElasticSearchConfig                             *ElasticSearchConfig
	GetAlerts200ResponseAllOfChecksInnerConfigAnyOf *GetAlerts200ResponseAllOfChecksInnerConfigAnyOf
	SNMPConfig                                      *SNMPConfig
	SQLConfig                                       *SQLConfig
	SocketConfig                                    *SocketConfig
	WebGetConfig                                    *WebGetConfig
	MapmapOfStringAny                               *map[string]interface{}
}

func (dst *GetAlerts200ResponseAllOfChecksInnerConfig) UnmarshalMapstructure(data any) (any, error) {
	if dst == nil {
		dst = &GetAlerts200ResponseAllOfChecksInnerConfig{}
	}

	mapstructDecode(data, &dst.ElasticSearchConfig)

	if IsEmpty(dst.ElasticSearchConfig) {
		dst.ElasticSearchConfig = nil
	}

	mapstructDecode(data, &dst.GetAlerts200ResponseAllOfChecksInnerConfigAnyOf)

	if IsEmpty(dst.GetAlerts200ResponseAllOfChecksInnerConfigAnyOf) {
		dst.GetAlerts200ResponseAllOfChecksInnerConfigAnyOf = nil
	}

	mapstructDecode(data, &dst.SNMPConfig)

	if IsEmpty(dst.SNMPConfig) {
		dst.SNMPConfig = nil
	}

	mapstructDecode(data, &dst.SQLConfig)

	if IsEmpty(dst.SQLConfig) {
		dst.SQLConfig = nil
	}

	mapstructDecode(data, &dst.SocketConfig)

	if IsEmpty(dst.SocketConfig) {
		dst.SocketConfig = nil
	}

	mapstructDecode(data, &dst.WebGetConfig)

	if IsEmpty(dst.WebGetConfig) {
		dst.WebGetConfig = nil
	}

	mapstructDecode(data, &dst.MapmapOfStringAny)

	if IsEmpty(dst.MapmapOfStringAny) {
		dst.MapmapOfStringAny = nil
	}

	return dst, nil
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetAlerts200ResponseAllOfChecksInnerConfig) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ElasticSearchConfig
	err = json.Unmarshal(data, &dst.ElasticSearchConfig)
	if err == nil {
		jsonElasticSearchConfig, merrElasticSearchConfig := json.Marshal(dst.ElasticSearchConfig)
		var zeroElasticSearchConfig ElasticSearchConfig
		jsonZeroElasticSearchConfig, _ := json.Marshal(&zeroElasticSearchConfig)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrElasticSearchConfig != nil || string(jsonElasticSearchConfig) == "{}" || (len(jsonElasticSearchConfig) > 0 && jsonElasticSearchConfig[0] == '{' && string(jsonElasticSearchConfig) == string(jsonZeroElasticSearchConfig)) {
			dst.ElasticSearchConfig = nil
		} else {
			return nil // data stored in dst.ElasticSearchConfig, return on the first match
		}
	} else {
		dst.ElasticSearchConfig = nil
	}

	// try to unmarshal JSON data into GetAlerts200ResponseAllOfChecksInnerConfigAnyOf
	err = json.Unmarshal(data, &dst.GetAlerts200ResponseAllOfChecksInnerConfigAnyOf)
	if err == nil {
		jsonGetAlerts200ResponseAllOfChecksInnerConfigAnyOf, merrGetAlerts200ResponseAllOfChecksInnerConfigAnyOf := json.Marshal(dst.GetAlerts200ResponseAllOfChecksInnerConfigAnyOf)
		var zeroGetAlerts200ResponseAllOfChecksInnerConfigAnyOf GetAlerts200ResponseAllOfChecksInnerConfigAnyOf
		jsonZeroGetAlerts200ResponseAllOfChecksInnerConfigAnyOf, _ := json.Marshal(&zeroGetAlerts200ResponseAllOfChecksInnerConfigAnyOf)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrGetAlerts200ResponseAllOfChecksInnerConfigAnyOf != nil || string(jsonGetAlerts200ResponseAllOfChecksInnerConfigAnyOf) == "{}" || (len(jsonGetAlerts200ResponseAllOfChecksInnerConfigAnyOf) > 0 && jsonGetAlerts200ResponseAllOfChecksInnerConfigAnyOf[0] == '{' && string(jsonGetAlerts200ResponseAllOfChecksInnerConfigAnyOf) == string(jsonZeroGetAlerts200ResponseAllOfChecksInnerConfigAnyOf)) {
			dst.GetAlerts200ResponseAllOfChecksInnerConfigAnyOf = nil
		} else {
			return nil // data stored in dst.GetAlerts200ResponseAllOfChecksInnerConfigAnyOf, return on the first match
		}
	} else {
		dst.GetAlerts200ResponseAllOfChecksInnerConfigAnyOf = nil
	}

	// try to unmarshal JSON data into SNMPConfig
	err = json.Unmarshal(data, &dst.SNMPConfig)
	if err == nil {
		jsonSNMPConfig, merrSNMPConfig := json.Marshal(dst.SNMPConfig)
		var zeroSNMPConfig SNMPConfig
		jsonZeroSNMPConfig, _ := json.Marshal(&zeroSNMPConfig)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrSNMPConfig != nil || string(jsonSNMPConfig) == "{}" || (len(jsonSNMPConfig) > 0 && jsonSNMPConfig[0] == '{' && string(jsonSNMPConfig) == string(jsonZeroSNMPConfig)) {
			dst.SNMPConfig = nil
		} else {
			return nil // data stored in dst.SNMPConfig, return on the first match
		}
	} else {
		dst.SNMPConfig = nil
	}

	// try to unmarshal JSON data into SQLConfig
	err = json.Unmarshal(data, &dst.SQLConfig)
	if err == nil {
		jsonSQLConfig, merrSQLConfig := json.Marshal(dst.SQLConfig)
		var zeroSQLConfig SQLConfig
		jsonZeroSQLConfig, _ := json.Marshal(&zeroSQLConfig)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrSQLConfig != nil || string(jsonSQLConfig) == "{}" || (len(jsonSQLConfig) > 0 && jsonSQLConfig[0] == '{' && string(jsonSQLConfig) == string(jsonZeroSQLConfig)) {
			dst.SQLConfig = nil
		} else {
			return nil // data stored in dst.SQLConfig, return on the first match
		}
	} else {
		dst.SQLConfig = nil
	}

	// try to unmarshal JSON data into SocketConfig
	err = json.Unmarshal(data, &dst.SocketConfig)
	if err == nil {
		jsonSocketConfig, merrSocketConfig := json.Marshal(dst.SocketConfig)
		var zeroSocketConfig SocketConfig
		jsonZeroSocketConfig, _ := json.Marshal(&zeroSocketConfig)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrSocketConfig != nil || string(jsonSocketConfig) == "{}" || (len(jsonSocketConfig) > 0 && jsonSocketConfig[0] == '{' && string(jsonSocketConfig) == string(jsonZeroSocketConfig)) {
			dst.SocketConfig = nil
		} else {
			return nil // data stored in dst.SocketConfig, return on the first match
		}
	} else {
		dst.SocketConfig = nil
	}

	// try to unmarshal JSON data into WebGetConfig
	err = json.Unmarshal(data, &dst.WebGetConfig)
	if err == nil {
		jsonWebGetConfig, merrWebGetConfig := json.Marshal(dst.WebGetConfig)
		var zeroWebGetConfig WebGetConfig
		jsonZeroWebGetConfig, _ := json.Marshal(&zeroWebGetConfig)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrWebGetConfig != nil || string(jsonWebGetConfig) == "{}" || (len(jsonWebGetConfig) > 0 && jsonWebGetConfig[0] == '{' && string(jsonWebGetConfig) == string(jsonZeroWebGetConfig)) {
			dst.WebGetConfig = nil
		} else {
			return nil // data stored in dst.WebGetConfig, return on the first match
		}
	} else {
		dst.WebGetConfig = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, merrMapmapOfStringAny := json.Marshal(dst.MapmapOfStringAny)
		var zeroMapmapOfStringAny map[string]interface{}
		jsonZeroMapmapOfStringAny, _ := json.Marshal(&zeroMapmapOfStringAny)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrMapmapOfStringAny != nil || string(jsonMapmapOfStringAny) == "{}" || (len(jsonMapmapOfStringAny) > 0 && jsonMapmapOfStringAny[0] == '{' && string(jsonMapmapOfStringAny) == string(jsonZeroMapmapOfStringAny)) {
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	// An empty object (or empty payload) legitimately matches no variant;
	// treat it as "no data" rather than a hard validation error so that an
	// empty value round-trips cleanly instead of failing to unmarshal.
	if string(data) == "{}" || string(data) == "" {
		return nil
	}
	return NewResponseValidationError("data failed to match schemas in anyOf(GetAlerts200ResponseAllOfChecksInnerConfig)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetAlerts200ResponseAllOfChecksInnerConfig) MarshalJSON() ([]byte, error) {
	if src.ElasticSearchConfig != nil {
		return json.Marshal(&src.ElasticSearchConfig)
	}

	if src.GetAlerts200ResponseAllOfChecksInnerConfigAnyOf != nil {
		return json.Marshal(&src.GetAlerts200ResponseAllOfChecksInnerConfigAnyOf)
	}

	if src.SNMPConfig != nil {
		return json.Marshal(&src.SNMPConfig)
	}

	if src.SQLConfig != nil {
		return json.Marshal(&src.SQLConfig)
	}

	if src.SocketConfig != nil {
		return json.Marshal(&src.SocketConfig)
	}

	if src.WebGetConfig != nil {
		return json.Marshal(&src.WebGetConfig)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return []byte("{}"), nil // no variant set: marshal an empty object rather than returning (nil,nil), which encoding/json rejects as "unexpected end of JSON input"
}

type NullableGetAlerts200ResponseAllOfChecksInnerConfig struct {
	value *GetAlerts200ResponseAllOfChecksInnerConfig
	isSet bool
}

func (v NullableGetAlerts200ResponseAllOfChecksInnerConfig) Get() *GetAlerts200ResponseAllOfChecksInnerConfig {
	return v.value
}

func (v *NullableGetAlerts200ResponseAllOfChecksInnerConfig) Set(val *GetAlerts200ResponseAllOfChecksInnerConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAlerts200ResponseAllOfChecksInnerConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAlerts200ResponseAllOfChecksInnerConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAlerts200ResponseAllOfChecksInnerConfig(val *GetAlerts200ResponseAllOfChecksInnerConfig) *NullableGetAlerts200ResponseAllOfChecksInnerConfig {
	return &NullableGetAlerts200ResponseAllOfChecksInnerConfig{value: val, isSet: true}
}

func (v NullableGetAlerts200ResponseAllOfChecksInnerConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAlerts200ResponseAllOfChecksInnerConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGetAlerts200ResponseAllOfChecksInnerConfig) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}
