/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// very silly way of avoiding `"fmt" imported and not used` errors
var _ fmt.Stringer

// InstanceCreateConfig struct for InstanceCreateConfig
type InstanceCreateConfig struct {
	AmazonInstanceConfiguration7      *AmazonInstanceConfiguration7
	AzureInstanceConfiguration7       *AzureInstanceConfiguration7
	BMaaSInstanceConfiguration1       *BMaaSInstanceConfiguration1
	GenericInstanceConfiguration7     *GenericInstanceConfiguration7
	GoogleCloudInstanceConfiguration7 *GoogleCloudInstanceConfiguration7
	HVMInstanceConfiguration2         *HVMInstanceConfiguration2
	VMWareInstanceConfiguration7      *VMWareInstanceConfiguration7
}

func (dst *InstanceCreateConfig) UnmarshalMapstructure(data any) (any, error) {
	if dst == nil {
		dst = &InstanceCreateConfig{}
	}

	mapstructDecode(data, &dst.AmazonInstanceConfiguration7)

	if IsEmpty(dst.AmazonInstanceConfiguration7) {
		dst.AmazonInstanceConfiguration7 = nil
	}

	mapstructDecode(data, &dst.AzureInstanceConfiguration7)

	if IsEmpty(dst.AzureInstanceConfiguration7) {
		dst.AzureInstanceConfiguration7 = nil
	}

	mapstructDecode(data, &dst.BMaaSInstanceConfiguration1)

	if IsEmpty(dst.BMaaSInstanceConfiguration1) {
		dst.BMaaSInstanceConfiguration1 = nil
	}

	mapstructDecode(data, &dst.GenericInstanceConfiguration7)

	if IsEmpty(dst.GenericInstanceConfiguration7) {
		dst.GenericInstanceConfiguration7 = nil
	}

	mapstructDecode(data, &dst.GoogleCloudInstanceConfiguration7)

	if IsEmpty(dst.GoogleCloudInstanceConfiguration7) {
		dst.GoogleCloudInstanceConfiguration7 = nil
	}

	mapstructDecode(data, &dst.HVMInstanceConfiguration2)

	if IsEmpty(dst.HVMInstanceConfiguration2) {
		dst.HVMInstanceConfiguration2 = nil
	}

	mapstructDecode(data, &dst.VMWareInstanceConfiguration7)

	if IsEmpty(dst.VMWareInstanceConfiguration7) {
		dst.VMWareInstanceConfiguration7 = nil
	}

	return dst, nil
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *InstanceCreateConfig) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AmazonInstanceConfiguration7
	err = json.Unmarshal(data, &dst.AmazonInstanceConfiguration7)
	if err == nil {
		jsonAmazonInstanceConfiguration7, merrAmazonInstanceConfiguration7 := json.Marshal(dst.AmazonInstanceConfiguration7)
		var zeroAmazonInstanceConfiguration7 AmazonInstanceConfiguration7
		jsonZeroAmazonInstanceConfiguration7, _ := json.Marshal(&zeroAmazonInstanceConfiguration7)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrAmazonInstanceConfiguration7 != nil || string(jsonAmazonInstanceConfiguration7) == "{}" || (len(jsonAmazonInstanceConfiguration7) > 0 && jsonAmazonInstanceConfiguration7[0] == '{' && string(jsonAmazonInstanceConfiguration7) == string(jsonZeroAmazonInstanceConfiguration7)) {
			dst.AmazonInstanceConfiguration7 = nil
		} else {
			return nil // data stored in dst.AmazonInstanceConfiguration7, return on the first match
		}
	} else {
		dst.AmazonInstanceConfiguration7 = nil
	}

	// try to unmarshal JSON data into AzureInstanceConfiguration7
	err = json.Unmarshal(data, &dst.AzureInstanceConfiguration7)
	if err == nil {
		jsonAzureInstanceConfiguration7, merrAzureInstanceConfiguration7 := json.Marshal(dst.AzureInstanceConfiguration7)
		var zeroAzureInstanceConfiguration7 AzureInstanceConfiguration7
		jsonZeroAzureInstanceConfiguration7, _ := json.Marshal(&zeroAzureInstanceConfiguration7)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrAzureInstanceConfiguration7 != nil || string(jsonAzureInstanceConfiguration7) == "{}" || (len(jsonAzureInstanceConfiguration7) > 0 && jsonAzureInstanceConfiguration7[0] == '{' && string(jsonAzureInstanceConfiguration7) == string(jsonZeroAzureInstanceConfiguration7)) {
			dst.AzureInstanceConfiguration7 = nil
		} else {
			return nil // data stored in dst.AzureInstanceConfiguration7, return on the first match
		}
	} else {
		dst.AzureInstanceConfiguration7 = nil
	}

	// try to unmarshal JSON data into BMaaSInstanceConfiguration1
	err = json.Unmarshal(data, &dst.BMaaSInstanceConfiguration1)
	if err == nil {
		jsonBMaaSInstanceConfiguration1, merrBMaaSInstanceConfiguration1 := json.Marshal(dst.BMaaSInstanceConfiguration1)
		var zeroBMaaSInstanceConfiguration1 BMaaSInstanceConfiguration1
		jsonZeroBMaaSInstanceConfiguration1, _ := json.Marshal(&zeroBMaaSInstanceConfiguration1)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrBMaaSInstanceConfiguration1 != nil || string(jsonBMaaSInstanceConfiguration1) == "{}" || (len(jsonBMaaSInstanceConfiguration1) > 0 && jsonBMaaSInstanceConfiguration1[0] == '{' && string(jsonBMaaSInstanceConfiguration1) == string(jsonZeroBMaaSInstanceConfiguration1)) {
			dst.BMaaSInstanceConfiguration1 = nil
		} else {
			return nil // data stored in dst.BMaaSInstanceConfiguration1, return on the first match
		}
	} else {
		dst.BMaaSInstanceConfiguration1 = nil
	}

	// try to unmarshal JSON data into GenericInstanceConfiguration7
	err = json.Unmarshal(data, &dst.GenericInstanceConfiguration7)
	if err == nil {
		jsonGenericInstanceConfiguration7, merrGenericInstanceConfiguration7 := json.Marshal(dst.GenericInstanceConfiguration7)
		var zeroGenericInstanceConfiguration7 GenericInstanceConfiguration7
		jsonZeroGenericInstanceConfiguration7, _ := json.Marshal(&zeroGenericInstanceConfiguration7)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrGenericInstanceConfiguration7 != nil || string(jsonGenericInstanceConfiguration7) == "{}" || (len(jsonGenericInstanceConfiguration7) > 0 && jsonGenericInstanceConfiguration7[0] == '{' && string(jsonGenericInstanceConfiguration7) == string(jsonZeroGenericInstanceConfiguration7)) {
			dst.GenericInstanceConfiguration7 = nil
		} else {
			return nil // data stored in dst.GenericInstanceConfiguration7, return on the first match
		}
	} else {
		dst.GenericInstanceConfiguration7 = nil
	}

	// try to unmarshal JSON data into GoogleCloudInstanceConfiguration7
	err = json.Unmarshal(data, &dst.GoogleCloudInstanceConfiguration7)
	if err == nil {
		jsonGoogleCloudInstanceConfiguration7, merrGoogleCloudInstanceConfiguration7 := json.Marshal(dst.GoogleCloudInstanceConfiguration7)
		var zeroGoogleCloudInstanceConfiguration7 GoogleCloudInstanceConfiguration7
		jsonZeroGoogleCloudInstanceConfiguration7, _ := json.Marshal(&zeroGoogleCloudInstanceConfiguration7)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrGoogleCloudInstanceConfiguration7 != nil || string(jsonGoogleCloudInstanceConfiguration7) == "{}" || (len(jsonGoogleCloudInstanceConfiguration7) > 0 && jsonGoogleCloudInstanceConfiguration7[0] == '{' && string(jsonGoogleCloudInstanceConfiguration7) == string(jsonZeroGoogleCloudInstanceConfiguration7)) {
			dst.GoogleCloudInstanceConfiguration7 = nil
		} else {
			return nil // data stored in dst.GoogleCloudInstanceConfiguration7, return on the first match
		}
	} else {
		dst.GoogleCloudInstanceConfiguration7 = nil
	}

	// try to unmarshal JSON data into HVMInstanceConfiguration2
	err = json.Unmarshal(data, &dst.HVMInstanceConfiguration2)
	if err == nil {
		jsonHVMInstanceConfiguration2, merrHVMInstanceConfiguration2 := json.Marshal(dst.HVMInstanceConfiguration2)
		var zeroHVMInstanceConfiguration2 HVMInstanceConfiguration2
		jsonZeroHVMInstanceConfiguration2, _ := json.Marshal(&zeroHVMInstanceConfiguration2)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrHVMInstanceConfiguration2 != nil || string(jsonHVMInstanceConfiguration2) == "{}" || (len(jsonHVMInstanceConfiguration2) > 0 && jsonHVMInstanceConfiguration2[0] == '{' && string(jsonHVMInstanceConfiguration2) == string(jsonZeroHVMInstanceConfiguration2)) {
			dst.HVMInstanceConfiguration2 = nil
		} else {
			return nil // data stored in dst.HVMInstanceConfiguration2, return on the first match
		}
	} else {
		dst.HVMInstanceConfiguration2 = nil
	}

	// try to unmarshal JSON data into VMWareInstanceConfiguration7
	err = json.Unmarshal(data, &dst.VMWareInstanceConfiguration7)
	if err == nil {
		jsonVMWareInstanceConfiguration7, merrVMWareInstanceConfiguration7 := json.Marshal(dst.VMWareInstanceConfiguration7)
		var zeroVMWareInstanceConfiguration7 VMWareInstanceConfiguration7
		jsonZeroVMWareInstanceConfiguration7, _ := json.Marshal(&zeroVMWareInstanceConfiguration7)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrVMWareInstanceConfiguration7 != nil || string(jsonVMWareInstanceConfiguration7) == "{}" || (len(jsonVMWareInstanceConfiguration7) > 0 && jsonVMWareInstanceConfiguration7[0] == '{' && string(jsonVMWareInstanceConfiguration7) == string(jsonZeroVMWareInstanceConfiguration7)) {
			dst.VMWareInstanceConfiguration7 = nil
		} else {
			return nil // data stored in dst.VMWareInstanceConfiguration7, return on the first match
		}
	} else {
		dst.VMWareInstanceConfiguration7 = nil
	}

	// An empty object (or empty payload) legitimately matches no variant;
	// treat it as "no data" rather than a hard validation error so that an
	// empty value round-trips cleanly instead of failing to unmarshal.
	if string(data) == "{}" || string(data) == "" {
		return nil
	}
	return NewResponseValidationError("data failed to match schemas in anyOf(InstanceCreateConfig)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src InstanceCreateConfig) MarshalJSON() ([]byte, error) {
	if src.AmazonInstanceConfiguration7 != nil {
		return json.Marshal(&src.AmazonInstanceConfiguration7)
	}

	if src.AzureInstanceConfiguration7 != nil {
		return json.Marshal(&src.AzureInstanceConfiguration7)
	}

	if src.BMaaSInstanceConfiguration1 != nil {
		return json.Marshal(&src.BMaaSInstanceConfiguration1)
	}

	if src.GenericInstanceConfiguration7 != nil {
		return json.Marshal(&src.GenericInstanceConfiguration7)
	}

	if src.GoogleCloudInstanceConfiguration7 != nil {
		return json.Marshal(&src.GoogleCloudInstanceConfiguration7)
	}

	if src.HVMInstanceConfiguration2 != nil {
		return json.Marshal(&src.HVMInstanceConfiguration2)
	}

	if src.VMWareInstanceConfiguration7 != nil {
		return json.Marshal(&src.VMWareInstanceConfiguration7)
	}

	return []byte("{}"), nil // no variant set: marshal an empty object rather than returning (nil,nil), which encoding/json rejects as "unexpected end of JSON input"
}

type NullableInstanceCreateConfig struct {
	value *InstanceCreateConfig
	isSet bool
}

func (v NullableInstanceCreateConfig) Get() *InstanceCreateConfig {
	return v.value
}

func (v *NullableInstanceCreateConfig) Set(val *InstanceCreateConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceCreateConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceCreateConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceCreateConfig(val *InstanceCreateConfig) *NullableInstanceCreateConfig {
	return &NullableInstanceCreateConfig{value: val, isSet: true}
}

func (v NullableInstanceCreateConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceCreateConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableInstanceCreateConfig) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}
