/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup{}

// UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup struct for UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup
type UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup struct {
	Id                   *int64                 `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup

func (o UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableUpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup struct {
	value *UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup
	isSet bool
}

func (v NullableUpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup) Get() *UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup {
	return v.value
}

func (v *NullableUpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup) Set(val *UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup(val *UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup) *NullableUpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup {
	return &NullableUpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup{value: val, isSet: true}
}

func (v NullableUpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *UpdateHostResize200ResponseAllOfServerInterfacesInnerNetworkGroup) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
