/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType{}

// ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType struct for ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType
type ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType struct {
	Id                   *int64                 `json:"id,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType

func (o ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType struct {
	value *ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType
	isSet bool
}

func (v NullableListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType) Get() *ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType {
	return v.value
}

func (v *NullableListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType) Set(val *ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType) {
	v.value = val
	v.isSet = true
}

func (v NullableListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType) IsSet() bool {
	return v.isSet
}

func (v *NullableListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType(val *ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType) *NullableListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType {
	return &NullableListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType{value: val, isSet: true}
}

func (v NullableListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *ListDatastoreTypes200ResponseDatastoreTypesInnerStorageServerType) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
