/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// very silly way of avoiding `"fmt" imported and not used` errors
var _ fmt.Stringer

// UpdateLoadBalancerProfileRequestLoadBalancerProfileConfig Configuration object with parameters that vary by serviceType.
type UpdateLoadBalancerProfileRequestLoadBalancerProfileConfig struct {
	ClientSSLLoadBalancerProfileConfig4           *ClientSSLLoadBalancerProfileConfig4
	CookiePersistenceLoadBalancerProfileConfig4   *CookiePersistenceLoadBalancerProfileConfig4
	FastTCPLoadBalancerProfileConfig4             *FastTCPLoadBalancerProfileConfig4
	FastUDPLoadBalancerProfileConfig4             *FastUDPLoadBalancerProfileConfig4
	GenericPersistenceLoadBalancerProfileConfig4  *GenericPersistenceLoadBalancerProfileConfig4
	HTTPLoadBalancerProfileConfig4                *HTTPLoadBalancerProfileConfig4
	ServerSSLLoadBalancerProfileConfig4           *ServerSSLLoadBalancerProfileConfig4
	SourceIPPersistenceLoadBalancerProfileConfig4 *SourceIPPersistenceLoadBalancerProfileConfig4
}

func (dst *UpdateLoadBalancerProfileRequestLoadBalancerProfileConfig) UnmarshalMapstructure(data any) (any, error) {
	if dst == nil {
		dst = &UpdateLoadBalancerProfileRequestLoadBalancerProfileConfig{}
	}

	mapstructDecode(data, &dst.ClientSSLLoadBalancerProfileConfig4)

	if IsEmpty(dst.ClientSSLLoadBalancerProfileConfig4) {
		dst.ClientSSLLoadBalancerProfileConfig4 = nil
	}

	mapstructDecode(data, &dst.CookiePersistenceLoadBalancerProfileConfig4)

	if IsEmpty(dst.CookiePersistenceLoadBalancerProfileConfig4) {
		dst.CookiePersistenceLoadBalancerProfileConfig4 = nil
	}

	mapstructDecode(data, &dst.FastTCPLoadBalancerProfileConfig4)

	if IsEmpty(dst.FastTCPLoadBalancerProfileConfig4) {
		dst.FastTCPLoadBalancerProfileConfig4 = nil
	}

	mapstructDecode(data, &dst.FastUDPLoadBalancerProfileConfig4)

	if IsEmpty(dst.FastUDPLoadBalancerProfileConfig4) {
		dst.FastUDPLoadBalancerProfileConfig4 = nil
	}

	mapstructDecode(data, &dst.GenericPersistenceLoadBalancerProfileConfig4)

	if IsEmpty(dst.GenericPersistenceLoadBalancerProfileConfig4) {
		dst.GenericPersistenceLoadBalancerProfileConfig4 = nil
	}

	mapstructDecode(data, &dst.HTTPLoadBalancerProfileConfig4)

	if IsEmpty(dst.HTTPLoadBalancerProfileConfig4) {
		dst.HTTPLoadBalancerProfileConfig4 = nil
	}

	mapstructDecode(data, &dst.ServerSSLLoadBalancerProfileConfig4)

	if IsEmpty(dst.ServerSSLLoadBalancerProfileConfig4) {
		dst.ServerSSLLoadBalancerProfileConfig4 = nil
	}

	mapstructDecode(data, &dst.SourceIPPersistenceLoadBalancerProfileConfig4)

	if IsEmpty(dst.SourceIPPersistenceLoadBalancerProfileConfig4) {
		dst.SourceIPPersistenceLoadBalancerProfileConfig4 = nil
	}

	return dst, nil
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *UpdateLoadBalancerProfileRequestLoadBalancerProfileConfig) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ClientSSLLoadBalancerProfileConfig4
	err = json.Unmarshal(data, &dst.ClientSSLLoadBalancerProfileConfig4)
	if err == nil {
		jsonClientSSLLoadBalancerProfileConfig4, merrClientSSLLoadBalancerProfileConfig4 := json.Marshal(dst.ClientSSLLoadBalancerProfileConfig4)
		var zeroClientSSLLoadBalancerProfileConfig4 ClientSSLLoadBalancerProfileConfig4
		jsonZeroClientSSLLoadBalancerProfileConfig4, _ := json.Marshal(&zeroClientSSLLoadBalancerProfileConfig4)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrClientSSLLoadBalancerProfileConfig4 != nil || string(jsonClientSSLLoadBalancerProfileConfig4) == "{}" || (len(jsonClientSSLLoadBalancerProfileConfig4) > 0 && jsonClientSSLLoadBalancerProfileConfig4[0] == '{' && string(jsonClientSSLLoadBalancerProfileConfig4) == string(jsonZeroClientSSLLoadBalancerProfileConfig4)) {
			dst.ClientSSLLoadBalancerProfileConfig4 = nil
		} else {
			return nil // data stored in dst.ClientSSLLoadBalancerProfileConfig4, return on the first match
		}
	} else {
		dst.ClientSSLLoadBalancerProfileConfig4 = nil
	}

	// try to unmarshal JSON data into CookiePersistenceLoadBalancerProfileConfig4
	err = json.Unmarshal(data, &dst.CookiePersistenceLoadBalancerProfileConfig4)
	if err == nil {
		jsonCookiePersistenceLoadBalancerProfileConfig4, merrCookiePersistenceLoadBalancerProfileConfig4 := json.Marshal(dst.CookiePersistenceLoadBalancerProfileConfig4)
		var zeroCookiePersistenceLoadBalancerProfileConfig4 CookiePersistenceLoadBalancerProfileConfig4
		jsonZeroCookiePersistenceLoadBalancerProfileConfig4, _ := json.Marshal(&zeroCookiePersistenceLoadBalancerProfileConfig4)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrCookiePersistenceLoadBalancerProfileConfig4 != nil || string(jsonCookiePersistenceLoadBalancerProfileConfig4) == "{}" || (len(jsonCookiePersistenceLoadBalancerProfileConfig4) > 0 && jsonCookiePersistenceLoadBalancerProfileConfig4[0] == '{' && string(jsonCookiePersistenceLoadBalancerProfileConfig4) == string(jsonZeroCookiePersistenceLoadBalancerProfileConfig4)) {
			dst.CookiePersistenceLoadBalancerProfileConfig4 = nil
		} else {
			return nil // data stored in dst.CookiePersistenceLoadBalancerProfileConfig4, return on the first match
		}
	} else {
		dst.CookiePersistenceLoadBalancerProfileConfig4 = nil
	}

	// try to unmarshal JSON data into FastTCPLoadBalancerProfileConfig4
	err = json.Unmarshal(data, &dst.FastTCPLoadBalancerProfileConfig4)
	if err == nil {
		jsonFastTCPLoadBalancerProfileConfig4, merrFastTCPLoadBalancerProfileConfig4 := json.Marshal(dst.FastTCPLoadBalancerProfileConfig4)
		var zeroFastTCPLoadBalancerProfileConfig4 FastTCPLoadBalancerProfileConfig4
		jsonZeroFastTCPLoadBalancerProfileConfig4, _ := json.Marshal(&zeroFastTCPLoadBalancerProfileConfig4)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrFastTCPLoadBalancerProfileConfig4 != nil || string(jsonFastTCPLoadBalancerProfileConfig4) == "{}" || (len(jsonFastTCPLoadBalancerProfileConfig4) > 0 && jsonFastTCPLoadBalancerProfileConfig4[0] == '{' && string(jsonFastTCPLoadBalancerProfileConfig4) == string(jsonZeroFastTCPLoadBalancerProfileConfig4)) {
			dst.FastTCPLoadBalancerProfileConfig4 = nil
		} else {
			return nil // data stored in dst.FastTCPLoadBalancerProfileConfig4, return on the first match
		}
	} else {
		dst.FastTCPLoadBalancerProfileConfig4 = nil
	}

	// try to unmarshal JSON data into FastUDPLoadBalancerProfileConfig4
	err = json.Unmarshal(data, &dst.FastUDPLoadBalancerProfileConfig4)
	if err == nil {
		jsonFastUDPLoadBalancerProfileConfig4, merrFastUDPLoadBalancerProfileConfig4 := json.Marshal(dst.FastUDPLoadBalancerProfileConfig4)
		var zeroFastUDPLoadBalancerProfileConfig4 FastUDPLoadBalancerProfileConfig4
		jsonZeroFastUDPLoadBalancerProfileConfig4, _ := json.Marshal(&zeroFastUDPLoadBalancerProfileConfig4)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrFastUDPLoadBalancerProfileConfig4 != nil || string(jsonFastUDPLoadBalancerProfileConfig4) == "{}" || (len(jsonFastUDPLoadBalancerProfileConfig4) > 0 && jsonFastUDPLoadBalancerProfileConfig4[0] == '{' && string(jsonFastUDPLoadBalancerProfileConfig4) == string(jsonZeroFastUDPLoadBalancerProfileConfig4)) {
			dst.FastUDPLoadBalancerProfileConfig4 = nil
		} else {
			return nil // data stored in dst.FastUDPLoadBalancerProfileConfig4, return on the first match
		}
	} else {
		dst.FastUDPLoadBalancerProfileConfig4 = nil
	}

	// try to unmarshal JSON data into GenericPersistenceLoadBalancerProfileConfig4
	err = json.Unmarshal(data, &dst.GenericPersistenceLoadBalancerProfileConfig4)
	if err == nil {
		jsonGenericPersistenceLoadBalancerProfileConfig4, merrGenericPersistenceLoadBalancerProfileConfig4 := json.Marshal(dst.GenericPersistenceLoadBalancerProfileConfig4)
		var zeroGenericPersistenceLoadBalancerProfileConfig4 GenericPersistenceLoadBalancerProfileConfig4
		jsonZeroGenericPersistenceLoadBalancerProfileConfig4, _ := json.Marshal(&zeroGenericPersistenceLoadBalancerProfileConfig4)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrGenericPersistenceLoadBalancerProfileConfig4 != nil || string(jsonGenericPersistenceLoadBalancerProfileConfig4) == "{}" || (len(jsonGenericPersistenceLoadBalancerProfileConfig4) > 0 && jsonGenericPersistenceLoadBalancerProfileConfig4[0] == '{' && string(jsonGenericPersistenceLoadBalancerProfileConfig4) == string(jsonZeroGenericPersistenceLoadBalancerProfileConfig4)) {
			dst.GenericPersistenceLoadBalancerProfileConfig4 = nil
		} else {
			return nil // data stored in dst.GenericPersistenceLoadBalancerProfileConfig4, return on the first match
		}
	} else {
		dst.GenericPersistenceLoadBalancerProfileConfig4 = nil
	}

	// try to unmarshal JSON data into HTTPLoadBalancerProfileConfig4
	err = json.Unmarshal(data, &dst.HTTPLoadBalancerProfileConfig4)
	if err == nil {
		jsonHTTPLoadBalancerProfileConfig4, merrHTTPLoadBalancerProfileConfig4 := json.Marshal(dst.HTTPLoadBalancerProfileConfig4)
		var zeroHTTPLoadBalancerProfileConfig4 HTTPLoadBalancerProfileConfig4
		jsonZeroHTTPLoadBalancerProfileConfig4, _ := json.Marshal(&zeroHTTPLoadBalancerProfileConfig4)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrHTTPLoadBalancerProfileConfig4 != nil || string(jsonHTTPLoadBalancerProfileConfig4) == "{}" || (len(jsonHTTPLoadBalancerProfileConfig4) > 0 && jsonHTTPLoadBalancerProfileConfig4[0] == '{' && string(jsonHTTPLoadBalancerProfileConfig4) == string(jsonZeroHTTPLoadBalancerProfileConfig4)) {
			dst.HTTPLoadBalancerProfileConfig4 = nil
		} else {
			return nil // data stored in dst.HTTPLoadBalancerProfileConfig4, return on the first match
		}
	} else {
		dst.HTTPLoadBalancerProfileConfig4 = nil
	}

	// try to unmarshal JSON data into ServerSSLLoadBalancerProfileConfig4
	err = json.Unmarshal(data, &dst.ServerSSLLoadBalancerProfileConfig4)
	if err == nil {
		jsonServerSSLLoadBalancerProfileConfig4, merrServerSSLLoadBalancerProfileConfig4 := json.Marshal(dst.ServerSSLLoadBalancerProfileConfig4)
		var zeroServerSSLLoadBalancerProfileConfig4 ServerSSLLoadBalancerProfileConfig4
		jsonZeroServerSSLLoadBalancerProfileConfig4, _ := json.Marshal(&zeroServerSSLLoadBalancerProfileConfig4)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrServerSSLLoadBalancerProfileConfig4 != nil || string(jsonServerSSLLoadBalancerProfileConfig4) == "{}" || (len(jsonServerSSLLoadBalancerProfileConfig4) > 0 && jsonServerSSLLoadBalancerProfileConfig4[0] == '{' && string(jsonServerSSLLoadBalancerProfileConfig4) == string(jsonZeroServerSSLLoadBalancerProfileConfig4)) {
			dst.ServerSSLLoadBalancerProfileConfig4 = nil
		} else {
			return nil // data stored in dst.ServerSSLLoadBalancerProfileConfig4, return on the first match
		}
	} else {
		dst.ServerSSLLoadBalancerProfileConfig4 = nil
	}

	// try to unmarshal JSON data into SourceIPPersistenceLoadBalancerProfileConfig4
	err = json.Unmarshal(data, &dst.SourceIPPersistenceLoadBalancerProfileConfig4)
	if err == nil {
		jsonSourceIPPersistenceLoadBalancerProfileConfig4, merrSourceIPPersistenceLoadBalancerProfileConfig4 := json.Marshal(dst.SourceIPPersistenceLoadBalancerProfileConfig4)
		var zeroSourceIPPersistenceLoadBalancerProfileConfig4 SourceIPPersistenceLoadBalancerProfileConfig4
		jsonZeroSourceIPPersistenceLoadBalancerProfileConfig4, _ := json.Marshal(&zeroSourceIPPersistenceLoadBalancerProfileConfig4)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrSourceIPPersistenceLoadBalancerProfileConfig4 != nil || string(jsonSourceIPPersistenceLoadBalancerProfileConfig4) == "{}" || (len(jsonSourceIPPersistenceLoadBalancerProfileConfig4) > 0 && jsonSourceIPPersistenceLoadBalancerProfileConfig4[0] == '{' && string(jsonSourceIPPersistenceLoadBalancerProfileConfig4) == string(jsonZeroSourceIPPersistenceLoadBalancerProfileConfig4)) {
			dst.SourceIPPersistenceLoadBalancerProfileConfig4 = nil
		} else {
			return nil // data stored in dst.SourceIPPersistenceLoadBalancerProfileConfig4, return on the first match
		}
	} else {
		dst.SourceIPPersistenceLoadBalancerProfileConfig4 = nil
	}

	// An empty object (or empty payload) legitimately matches no variant;
	// treat it as "no data" rather than a hard validation error so that an
	// empty value round-trips cleanly instead of failing to unmarshal.
	if string(data) == "{}" || string(data) == "" {
		return nil
	}
	return NewResponseValidationError("data failed to match schemas in anyOf(UpdateLoadBalancerProfileRequestLoadBalancerProfileConfig)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UpdateLoadBalancerProfileRequestLoadBalancerProfileConfig) MarshalJSON() ([]byte, error) {
	if src.ClientSSLLoadBalancerProfileConfig4 != nil {
		return json.Marshal(&src.ClientSSLLoadBalancerProfileConfig4)
	}

	if src.CookiePersistenceLoadBalancerProfileConfig4 != nil {
		return json.Marshal(&src.CookiePersistenceLoadBalancerProfileConfig4)
	}

	if src.FastTCPLoadBalancerProfileConfig4 != nil {
		return json.Marshal(&src.FastTCPLoadBalancerProfileConfig4)
	}

	if src.FastUDPLoadBalancerProfileConfig4 != nil {
		return json.Marshal(&src.FastUDPLoadBalancerProfileConfig4)
	}

	if src.GenericPersistenceLoadBalancerProfileConfig4 != nil {
		return json.Marshal(&src.GenericPersistenceLoadBalancerProfileConfig4)
	}

	if src.HTTPLoadBalancerProfileConfig4 != nil {
		return json.Marshal(&src.HTTPLoadBalancerProfileConfig4)
	}

	if src.ServerSSLLoadBalancerProfileConfig4 != nil {
		return json.Marshal(&src.ServerSSLLoadBalancerProfileConfig4)
	}

	if src.SourceIPPersistenceLoadBalancerProfileConfig4 != nil {
		return json.Marshal(&src.SourceIPPersistenceLoadBalancerProfileConfig4)
	}

	return []byte("{}"), nil // no variant set: marshal an empty object rather than returning (nil,nil), which encoding/json rejects as "unexpected end of JSON input"
}

type NullableUpdateLoadBalancerProfileRequestLoadBalancerProfileConfig struct {
	value *UpdateLoadBalancerProfileRequestLoadBalancerProfileConfig
	isSet bool
}

func (v NullableUpdateLoadBalancerProfileRequestLoadBalancerProfileConfig) Get() *UpdateLoadBalancerProfileRequestLoadBalancerProfileConfig {
	return v.value
}

func (v *NullableUpdateLoadBalancerProfileRequestLoadBalancerProfileConfig) Set(val *UpdateLoadBalancerProfileRequestLoadBalancerProfileConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateLoadBalancerProfileRequestLoadBalancerProfileConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateLoadBalancerProfileRequestLoadBalancerProfileConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateLoadBalancerProfileRequestLoadBalancerProfileConfig(val *UpdateLoadBalancerProfileRequestLoadBalancerProfileConfig) *NullableUpdateLoadBalancerProfileRequestLoadBalancerProfileConfig {
	return &NullableUpdateLoadBalancerProfileRequestLoadBalancerProfileConfig{value: val, isSet: true}
}

func (v NullableUpdateLoadBalancerProfileRequestLoadBalancerProfileConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateLoadBalancerProfileRequestLoadBalancerProfileConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableUpdateLoadBalancerProfileRequestLoadBalancerProfileConfig) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}
