/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the GetScript200ResponseContainerScriptAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetScript200ResponseContainerScriptAccount{}

// GetScript200ResponseContainerScriptAccount struct for GetScript200ResponseContainerScriptAccount
type GetScript200ResponseContainerScriptAccount struct {
	Id                   *int64                 `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _GetScript200ResponseContainerScriptAccount GetScript200ResponseContainerScriptAccount

func (o GetScript200ResponseContainerScriptAccount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetScript200ResponseContainerScriptAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableGetScript200ResponseContainerScriptAccount struct {
	value *GetScript200ResponseContainerScriptAccount
	isSet bool
}

func (v NullableGetScript200ResponseContainerScriptAccount) Get() *GetScript200ResponseContainerScriptAccount {
	return v.value
}

func (v *NullableGetScript200ResponseContainerScriptAccount) Set(val *GetScript200ResponseContainerScriptAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableGetScript200ResponseContainerScriptAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableGetScript200ResponseContainerScriptAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetScript200ResponseContainerScriptAccount(val *GetScript200ResponseContainerScriptAccount) *NullableGetScript200ResponseContainerScriptAccount {
	return &NullableGetScript200ResponseContainerScriptAccount{value: val, isSet: true}
}

func (v NullableGetScript200ResponseContainerScriptAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetScript200ResponseContainerScriptAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableGetScript200ResponseContainerScriptAccount) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *GetScript200ResponseContainerScriptAccount) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
