/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the BMaaSInstanceConfiguration1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BMaaSInstanceConfiguration1{}

// BMaaSInstanceConfiguration1 Configuration options for HPE bare metal (BMaaS) instances.
type BMaaSInstanceConfiguration1 struct {
	// The id of the ISO virtual image to boot the bare metal instance from.
	ImageId int64 `json:"imageId"`
	// id of the resource pool to provision into, can be prefixed with `pool-`. A resource pool group can be specified instead by prefixing its ID with `poolGroup-`.
	ResourcePoolId *string `json:"resourcePoolId,omitempty"`
	// Whether to create a user when provisioning the instance.
	CreateUser NullableBool `json:"createUser,omitempty"`
	// Skipping Agent installation will result in a lack of logging and guest operating system statistics. Automation scripts may also be adversely affected.
	NoAgent NullableBool `json:"noAgent,omitempty"`
	// When enabled, provisioning fails if a RAID boot volume cannot be created. When disabled, provisioning falls back to a single disk if RAID1 is unavailable.
	EnforceRaidBootVolume *bool `json:"enforceRaidBootVolume,omitempty"`
	// The bare metal host(s) to provision this workload on. Each item wraps the host id in a `value` field (the baremetal plugin reads each selected host as `host.value`).
	SelectedHosts        []InstancesConfigBMaaSSelectedHostsInner `json:"selectedHosts,omitempty"`
	AdditionalProperties map[string]interface{}                   `json:",remain"`
}

type _BMaaSInstanceConfiguration1 BMaaSInstanceConfiguration1

func (o BMaaSInstanceConfiguration1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BMaaSInstanceConfiguration1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["imageId"] = o.ImageId
	if !IsNil(o.ResourcePoolId) {
		toSerialize["resourcePoolId"] = o.ResourcePoolId
	}
	if o.CreateUser.IsSet() {
		toSerialize["createUser"] = o.CreateUser.Get()
	}
	if o.NoAgent.IsSet() {
		toSerialize["noAgent"] = o.NoAgent.Get()
	}
	if !IsNil(o.EnforceRaidBootVolume) {
		toSerialize["enforceRaidBootVolume"] = o.EnforceRaidBootVolume
	}
	if !IsNil(o.SelectedHosts) {
		toSerialize["selectedHosts"] = o.SelectedHosts
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableBMaaSInstanceConfiguration1 struct {
	value *BMaaSInstanceConfiguration1
	isSet bool
}

func (v NullableBMaaSInstanceConfiguration1) Get() *BMaaSInstanceConfiguration1 {
	return v.value
}

func (v *NullableBMaaSInstanceConfiguration1) Set(val *BMaaSInstanceConfiguration1) {
	v.value = val
	v.isSet = true
}

func (v NullableBMaaSInstanceConfiguration1) IsSet() bool {
	return v.isSet
}

func (v *NullableBMaaSInstanceConfiguration1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBMaaSInstanceConfiguration1(val *BMaaSInstanceConfiguration1) *NullableBMaaSInstanceConfiguration1 {
	return &NullableBMaaSInstanceConfiguration1{value: val, isSet: true}
}

func (v NullableBMaaSInstanceConfiguration1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBMaaSInstanceConfiguration1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableBMaaSInstanceConfiguration1) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *BMaaSInstanceConfiguration1) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
