/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// very silly way of avoiding `"fmt" imported and not used` errors
var _ fmt.Stringer

// ListClouds200ResponseAllOfZonesInnerConfig struct for ListClouds200ResponseAllOfZonesInnerConfig
type ListClouds200ResponseAllOfZonesInnerConfig struct {
	ListClouds200ResponseAllOfZonesInnerConfigAnyOf  *ListClouds200ResponseAllOfZonesInnerConfigAnyOf
	ListClouds200ResponseAllOfZonesInnerConfigAnyOf1 *ListClouds200ResponseAllOfZonesInnerConfigAnyOf1
	ListClouds200ResponseAllOfZonesInnerConfigAnyOf2 *ListClouds200ResponseAllOfZonesInnerConfigAnyOf2
	ListClouds200ResponseAllOfZonesInnerConfigAnyOf3 *ListClouds200ResponseAllOfZonesInnerConfigAnyOf3
	MapmapOfStringAny                                *map[string]interface{}
}

func (dst *ListClouds200ResponseAllOfZonesInnerConfig) UnmarshalMapstructure(data any) (any, error) {
	if dst == nil {
		dst = &ListClouds200ResponseAllOfZonesInnerConfig{}
	}

	mapstructDecode(data, &dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf)

	if IsEmpty(dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf) {
		dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf = nil
	}

	mapstructDecode(data, &dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf1)

	if IsEmpty(dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf1) {
		dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf1 = nil
	}

	mapstructDecode(data, &dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf2)

	if IsEmpty(dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf2) {
		dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf2 = nil
	}

	mapstructDecode(data, &dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf3)

	if IsEmpty(dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf3) {
		dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf3 = nil
	}

	mapstructDecode(data, &dst.MapmapOfStringAny)

	if IsEmpty(dst.MapmapOfStringAny) {
		dst.MapmapOfStringAny = nil
	}

	return dst, nil
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ListClouds200ResponseAllOfZonesInnerConfig) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ListClouds200ResponseAllOfZonesInnerConfigAnyOf
	err = json.Unmarshal(data, &dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf)
	if err == nil {
		jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf, merrListClouds200ResponseAllOfZonesInnerConfigAnyOf := json.Marshal(dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf)
		var zeroListClouds200ResponseAllOfZonesInnerConfigAnyOf ListClouds200ResponseAllOfZonesInnerConfigAnyOf
		jsonZeroListClouds200ResponseAllOfZonesInnerConfigAnyOf, _ := json.Marshal(&zeroListClouds200ResponseAllOfZonesInnerConfigAnyOf)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrListClouds200ResponseAllOfZonesInnerConfigAnyOf != nil || string(jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf) == "{}" || (len(jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf) > 0 && jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf[0] == '{' && string(jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf) == string(jsonZeroListClouds200ResponseAllOfZonesInnerConfigAnyOf)) {
			dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf = nil
		} else {
			return nil // data stored in dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf, return on the first match
		}
	} else {
		dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf = nil
	}

	// try to unmarshal JSON data into ListClouds200ResponseAllOfZonesInnerConfigAnyOf1
	err = json.Unmarshal(data, &dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf1)
	if err == nil {
		jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf1, merrListClouds200ResponseAllOfZonesInnerConfigAnyOf1 := json.Marshal(dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf1)
		var zeroListClouds200ResponseAllOfZonesInnerConfigAnyOf1 ListClouds200ResponseAllOfZonesInnerConfigAnyOf1
		jsonZeroListClouds200ResponseAllOfZonesInnerConfigAnyOf1, _ := json.Marshal(&zeroListClouds200ResponseAllOfZonesInnerConfigAnyOf1)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrListClouds200ResponseAllOfZonesInnerConfigAnyOf1 != nil || string(jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf1) == "{}" || (len(jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf1) > 0 && jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf1[0] == '{' && string(jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf1) == string(jsonZeroListClouds200ResponseAllOfZonesInnerConfigAnyOf1)) {
			dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf1 = nil
		} else {
			return nil // data stored in dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf1, return on the first match
		}
	} else {
		dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf1 = nil
	}

	// try to unmarshal JSON data into ListClouds200ResponseAllOfZonesInnerConfigAnyOf2
	err = json.Unmarshal(data, &dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf2)
	if err == nil {
		jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf2, merrListClouds200ResponseAllOfZonesInnerConfigAnyOf2 := json.Marshal(dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf2)
		var zeroListClouds200ResponseAllOfZonesInnerConfigAnyOf2 ListClouds200ResponseAllOfZonesInnerConfigAnyOf2
		jsonZeroListClouds200ResponseAllOfZonesInnerConfigAnyOf2, _ := json.Marshal(&zeroListClouds200ResponseAllOfZonesInnerConfigAnyOf2)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrListClouds200ResponseAllOfZonesInnerConfigAnyOf2 != nil || string(jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf2) == "{}" || (len(jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf2) > 0 && jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf2[0] == '{' && string(jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf2) == string(jsonZeroListClouds200ResponseAllOfZonesInnerConfigAnyOf2)) {
			dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf2 = nil
		} else {
			return nil // data stored in dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf2, return on the first match
		}
	} else {
		dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf2 = nil
	}

	// try to unmarshal JSON data into ListClouds200ResponseAllOfZonesInnerConfigAnyOf3
	err = json.Unmarshal(data, &dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf3)
	if err == nil {
		jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf3, merrListClouds200ResponseAllOfZonesInnerConfigAnyOf3 := json.Marshal(dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf3)
		var zeroListClouds200ResponseAllOfZonesInnerConfigAnyOf3 ListClouds200ResponseAllOfZonesInnerConfigAnyOf3
		jsonZeroListClouds200ResponseAllOfZonesInnerConfigAnyOf3, _ := json.Marshal(&zeroListClouds200ResponseAllOfZonesInnerConfigAnyOf3)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrListClouds200ResponseAllOfZonesInnerConfigAnyOf3 != nil || string(jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf3) == "{}" || (len(jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf3) > 0 && jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf3[0] == '{' && string(jsonListClouds200ResponseAllOfZonesInnerConfigAnyOf3) == string(jsonZeroListClouds200ResponseAllOfZonesInnerConfigAnyOf3)) {
			dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf3 = nil
		} else {
			return nil // data stored in dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf3, return on the first match
		}
	} else {
		dst.ListClouds200ResponseAllOfZonesInnerConfigAnyOf3 = nil
	}

	// try to unmarshal JSON data into MapmapOfStringAny
	err = json.Unmarshal(data, &dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, merrMapmapOfStringAny := json.Marshal(dst.MapmapOfStringAny)
		var zeroMapmapOfStringAny map[string]interface{}
		jsonZeroMapmapOfStringAny, _ := json.Marshal(&zeroMapmapOfStringAny)
		// Reject a candidate variant when marshalling fails, when it is the
		// empty object, or when an OBJECT-valued variant round-trips to its
		// zero value (a false match on a struct with required fields). A
		// primitive variant (whose JSON does not start with '{') is never
		// rejected by the zero-value compare, so false/0/"" are preserved.
		if merrMapmapOfStringAny != nil || string(jsonMapmapOfStringAny) == "{}" || (len(jsonMapmapOfStringAny) > 0 && jsonMapmapOfStringAny[0] == '{' && string(jsonMapmapOfStringAny) == string(jsonZeroMapmapOfStringAny)) {
			dst.MapmapOfStringAny = nil
		} else {
			return nil // data stored in dst.MapmapOfStringAny, return on the first match
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	// An empty object (or empty payload) legitimately matches no variant;
	// treat it as "no data" rather than a hard validation error so that an
	// empty value round-trips cleanly instead of failing to unmarshal.
	if string(data) == "{}" || string(data) == "" {
		return nil
	}
	return NewResponseValidationError("data failed to match schemas in anyOf(ListClouds200ResponseAllOfZonesInnerConfig)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ListClouds200ResponseAllOfZonesInnerConfig) MarshalJSON() ([]byte, error) {
	if src.ListClouds200ResponseAllOfZonesInnerConfigAnyOf != nil {
		return json.Marshal(&src.ListClouds200ResponseAllOfZonesInnerConfigAnyOf)
	}

	if src.ListClouds200ResponseAllOfZonesInnerConfigAnyOf1 != nil {
		return json.Marshal(&src.ListClouds200ResponseAllOfZonesInnerConfigAnyOf1)
	}

	if src.ListClouds200ResponseAllOfZonesInnerConfigAnyOf2 != nil {
		return json.Marshal(&src.ListClouds200ResponseAllOfZonesInnerConfigAnyOf2)
	}

	if src.ListClouds200ResponseAllOfZonesInnerConfigAnyOf3 != nil {
		return json.Marshal(&src.ListClouds200ResponseAllOfZonesInnerConfigAnyOf3)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return []byte("{}"), nil // no variant set: marshal an empty object rather than returning (nil,nil), which encoding/json rejects as "unexpected end of JSON input"
}

type NullableListClouds200ResponseAllOfZonesInnerConfig struct {
	value *ListClouds200ResponseAllOfZonesInnerConfig
	isSet bool
}

func (v NullableListClouds200ResponseAllOfZonesInnerConfig) Get() *ListClouds200ResponseAllOfZonesInnerConfig {
	return v.value
}

func (v *NullableListClouds200ResponseAllOfZonesInnerConfig) Set(val *ListClouds200ResponseAllOfZonesInnerConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableListClouds200ResponseAllOfZonesInnerConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableListClouds200ResponseAllOfZonesInnerConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListClouds200ResponseAllOfZonesInnerConfig(val *ListClouds200ResponseAllOfZonesInnerConfig) *NullableListClouds200ResponseAllOfZonesInnerConfig {
	return &NullableListClouds200ResponseAllOfZonesInnerConfig{value: val, isSet: true}
}

func (v NullableListClouds200ResponseAllOfZonesInnerConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListClouds200ResponseAllOfZonesInnerConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableListClouds200ResponseAllOfZonesInnerConfig) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}
