/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ListScripts200ResponseAllOfContainerScriptsInnerAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListScripts200ResponseAllOfContainerScriptsInnerAccount{}

// ListScripts200ResponseAllOfContainerScriptsInnerAccount struct for ListScripts200ResponseAllOfContainerScriptsInnerAccount
type ListScripts200ResponseAllOfContainerScriptsInnerAccount struct {
	Id                   *int64                 `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _ListScripts200ResponseAllOfContainerScriptsInnerAccount ListScripts200ResponseAllOfContainerScriptsInnerAccount

func (o ListScripts200ResponseAllOfContainerScriptsInnerAccount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListScripts200ResponseAllOfContainerScriptsInnerAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableListScripts200ResponseAllOfContainerScriptsInnerAccount struct {
	value *ListScripts200ResponseAllOfContainerScriptsInnerAccount
	isSet bool
}

func (v NullableListScripts200ResponseAllOfContainerScriptsInnerAccount) Get() *ListScripts200ResponseAllOfContainerScriptsInnerAccount {
	return v.value
}

func (v *NullableListScripts200ResponseAllOfContainerScriptsInnerAccount) Set(val *ListScripts200ResponseAllOfContainerScriptsInnerAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableListScripts200ResponseAllOfContainerScriptsInnerAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableListScripts200ResponseAllOfContainerScriptsInnerAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListScripts200ResponseAllOfContainerScriptsInnerAccount(val *ListScripts200ResponseAllOfContainerScriptsInnerAccount) *NullableListScripts200ResponseAllOfContainerScriptsInnerAccount {
	return &NullableListScripts200ResponseAllOfContainerScriptsInnerAccount{value: val, isSet: true}
}

func (v NullableListScripts200ResponseAllOfContainerScriptsInnerAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListScripts200ResponseAllOfContainerScriptsInnerAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableListScripts200ResponseAllOfContainerScriptsInnerAccount) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *ListScripts200ResponseAllOfContainerScriptsInnerAccount) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
