/*
Morpheus API

Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

API version: 9.0.0
Contact: dev@morpheusdata.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer{}

// ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer The storage server the volume is provisioned on.
type ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer struct {
	Id                   *int64                 `json:"id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	AdditionalProperties map[string]interface{} `json:",remain"`
}

type _ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer

func (o ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

type NullableListClusterVolumes200ResponseAllOfVolumesInnerStorageServer struct {
	value *ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer
	isSet bool
}

func (v NullableListClusterVolumes200ResponseAllOfVolumesInnerStorageServer) Get() *ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer {
	return v.value
}

func (v *NullableListClusterVolumes200ResponseAllOfVolumesInnerStorageServer) Set(val *ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer) {
	v.value = val
	v.isSet = true
}

func (v NullableListClusterVolumes200ResponseAllOfVolumesInnerStorageServer) IsSet() bool {
	return v.isSet
}

func (v *NullableListClusterVolumes200ResponseAllOfVolumesInnerStorageServer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListClusterVolumes200ResponseAllOfVolumesInnerStorageServer(val *ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer) *NullableListClusterVolumes200ResponseAllOfVolumesInnerStorageServer {
	return &NullableListClusterVolumes200ResponseAllOfVolumesInnerStorageServer{value: val, isSet: true}
}

func (v NullableListClusterVolumes200ResponseAllOfVolumesInnerStorageServer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListClusterVolumes200ResponseAllOfVolumesInnerStorageServer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

func (v NullableListClusterVolumes200ResponseAllOfVolumesInnerStorageServer) UnmarshalMapstructure(data any) (any, error) {
	if err := mapstructDecode(data, &v.value); err != nil {
		return nil, err
	}
	v.isSet = true

	return v, nil
}

func (o *ListClusterVolumes200ResponseAllOfVolumesInnerStorageServer) UnmarshalJSON(data []byte) (err error) {
	return decode(data, &o)
}

// - model_simple.mustache
