# Copyright 2025 Hewlett Packard Enterprise Development LP

name: DocsDiff

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  diff:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go: [ '1.24.1' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - run: go version
      - run: terraform version
      - run: make docs
      - run: |
        echo "Checking all doc files are in sync with checked-in"
        status="$(git status --short)"
        if [[ ! -z $status ]]
        then
            echo "some doc files are out of sync or missing"
            echo "run `make docs` and commit the changes"
            echo "$status"
            exit 1
        fi
        echo "Input and generated seem up-to-date"
