# Copyright 2025 Hewlett Packard Enterprise Development LP

name: Docs

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - run: go version
      - run: terraform version
      - run: make docs
