# Copyright 2025 Hewlett Packard Enterprise Development LP

name: Test

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go version
      - run: make unit-tests
